xaynetwork/xaynet

xain/benchmark/aggregation.py
xain/benchmark/benchmark.py
xain/benchmark/benchmark_test.py
xain/benchmark/task.py

Benchmarks can now be configured using new `Benchmark` and `Task` abstractions. Implementation of aggregation functions and feature parity with current benchmarks will follow in subsequent PRs.

Create foundation for configurable benchmark package

---

.circleci/config.yml
.gitignore
xain/__init__.py
xain/benchmark/__init__.py
xain/config.py
xain/datasets/__init__.py
xain/helpers/project.py
xain/ops/conftest.py
xain/ops/results.py
xain/ops/results_test.py

This change will automatically init a global config file in project root where the user can centrally configure the project
Some config flags will serve as defaults for various abseil flags

Add file based global config setup

---

.clang-format
scripts/format.sh
scripts/test.sh

- remove .clang-format and hardcode the style

Fix clang invocation

---

xain/benchmark/exec/run.py
xain/fl/coordinator/aggregate.py
xain/fl/coordinator/coordinator.py
xain/fl/participant/participant.py

Fixes various pylint errors which where previously not showing up as a `__init__.py` was missing in fl package

Fix for pylint errors

---

setup.py

Simply removes obsolete entry points. Please merge if its fine.

Remove unused entry_points

---

xain/benchmark/exec/run.py
xain/fl/coordinator/aggregate.py
xain/fl/coordinator/coordinator.py
xain/fl/coordinator/evaluator.py
xain/fl/participant/participant.py
xain/types/__init__.py

...to make clear that they are not inherently dependent on Keras.

Rename two types

---

xain/benchmark/exec/run.py
xain/datasets/prep.py
xain/fl/coordinator/aggregate.py
xain/fl/coordinator/coordinator.py
xain/fl/coordinator/evaluator.py
xain/fl/participant/participant.py
xain/types/__init__.py

Improve typing consistency

---

xain/benchmark/exec/run.py
xain/datasets/prep.py
xain/datasets/stats/stats.py
xain/fl/coordinator/aggregate.py
xain/fl/coordinator/coordinator.py
xain/fl/coordinator/evaluator.py
xain/fl/participant/participant.py
xain/types/__init__.py

Please review #89 and #90 first (in that order).

Rename FederatedDatasetPartition to Partition

---

xain/benchmark/exec/__main__.py

As requested by @PanicButtonPressed, in preparation for plotting the selected participants in each round.

Write number of participants to results

---

xain/CONFIG.md

Feel free to modify and/or merge

Add short doc explaining the configuration module

---

setup.py
xain/__version__.py

Add a `__version__.py` file to work as a central place for all versioning needs.
This makes it less error prone when making new releases since we only need to update versions in a single place.

Added versioning support to the package

---

CHANGELOG.md

This merge request just adds a `CHANGELOG.md` so that we can document notable between versions.

Added a changelog to the project

---

CHANGELOG.md
README.md
scripts/setup.sh

- CHANGELOG versions are now links to the list of pr's merged since
the last release
- added pypi, circleci and license badges to the README
- fixed scripts/setup.sh to remove cpu extra

Cosmetic changes to CHANGELOG and README

---

Dockerfile

Fixes broken docker build. A followup will be to add an e2e test for docker builds as we are currently in CI not testing if the image can still be build.

Fixes broken docker build

---

examples/tensorflow_hello_world/helloworld.py

please see line 12. any better solution? thanks

initial version of fully working helloworld example

---

.circleci/config.yml

This removes the CI job for the rust tests.

Removed CI job for testing rust code

---

CODEOWNERS

Adding @finiteprods as a grpc code owner.

Added @finitprods to grpc code owners

---

examples/tensorflow_hello_world/helloworld.py

Sorry, when working through the latest comments on my last PR yesterday i missed this bit. Maybe it should have been picked up by some test?

bugfix: do use DATASET_NAME constant

---

scripts/setup_pyenv.sh

Co-authored-by: Daniel J. Beutel <daniel.beutel@xain.io>
Co-authored-by: Taner Topal <taner.topal@xain.io>

Script to setup pyenv

---

README.md
docs/index.rst

Fix badge versions and style
* set version to `latest` and style to `flat-square` in `README.md` and `index.rst`
No
---

Hotfix badge versions and style

---

README.md

https://xainag.atlassian.net/browse/XP-167
Created gitter community and added link to README.md
No

XP-167 Add gitter badge

---

README.md
docs/Makefile

https://xainag.atlassian.net/browse/XP-300
Add `make show` docs feature to show docs.
Update readme
No
---

XP-300 Update docs makefile

---

README.md
docs/Makefile
scripts/test.sh

https://xainag.atlassian.net/browse/XP-334
Add `make docs` command to cleanup and generate sphinx docs.
Update `scripts/test.sh`
No
---

XP-334 Add make docs into docs make file

---

README.md

https://xainag.atlassian.net/browse/XP-229
Update readme
No
---

XP-229 Update readme

---

benchmarks/benchmark/exec/run.py
examples/tensorflow_hello_world/helloworld.py
xain_fl/fl/coordinator/__init__.py
xain_fl/fl/coordinator/controller.py
xain_fl/fl/coordinator/controller_test.py
xain_fl/fl/coordinator/coordinator.py
xain_fl/grpc/cli.py
xain_fl/grpc/conftest.py
xain_fl/grpc/coordinator.py
xain_fl/grpc/test_coordinator.py
xain_fl/grpc/test_grpc.py

[XP-238](https://xainag.atlassian.net/browse/XP-238)
Implements Participant selection in the Coordinator
None

Xp 238 participant selection retry

---

README.md

https://xainag.atlassian.net/browse/XP-229
Update readme according to latest corrections.
No
---

XP-229 Update Readme.md

---

setup.py

https://xainag.atlassian.net/browse/XP-168
Update linters, formatters, freeze versions.
No
---

XP-168 Update linters/formatters

---

.github/workflows/development-e2e-tests.yml
.github/workflows/development.yml
.github/workflows/master.yml

[DO-35](https://xainag.atlassian.net/browse/DO-35)
Add placeholder for manual e2e tests on PRs to development branch. Add CI jobs on PRs to master
No
---

DO-35 :newspaper: :sparkles: Add placeholder for e2e

---

setup.py

[XP-424 Remove unused packages](https://xainag.atlassian.net/browse/XP-424)
* Removed `rope` and `requests`
---

XP-424 Remove unused packages

---

README.md

[XP-433 Fix docker headings in xain-fl](https://xainag.atlassian.net/browse/XP-433)
* Replaced H2 to H4 headings
No
---

XP-433 Fix docker headings

---

README.md

[XP-508 Add/Replace old circleCI badge](https://xainag.atlassian.net/browse/XP-508)
* replaced CircleCI badge with Github workflow badge
No
---

XP-508 Replace circleci badge

---

CHANGELOG.md
setup.py
xain_fl/__version__.py

[XP-227](https://xainag.atlassian.net/browse/XP-227) and [XP-356](https://xainag.atlassian.net/browse/XP-356)
Preparation for publishing xain-fl v0.3.0, matching same version for xain-sdk and xain-proto.
No
---

Prepare release of v0.3.0 (matching version with `xain-sdk` and `xain-proto`)

---

xain_fl/serve.py

https://xainag.atlassian.net/browse/PB-387
Start `monitor_hearbeats()` in the main thread instead of a background
thread. Motivations:
- code simplification.
- the current implementation with a background thread feels a little
hacky: we have an infinite loop in which we just sleep for very long
periods
- using threads is not strictly necessary here and leads to
complications (additional error handling, synchronisation etc.)
which may currently not be handled correctly:
1. the `monitor_thread` thread does not have the `daemon` flag
set, so it might keep the entie program alive if for some
reason it does not terminate
2. `Thread.join()` and `Thread.isAlive()` are not called, so we do
not know if the thread exited properly
---
* Reviewers assign themselves at the start …

PB-387 simplify serve module

---

.github/workflows/development_pull_request.yml
.github/workflows/master_pull_request.yml
scripts/format.sh
scripts/test.sh
tests/conftest.py
tests/controller_test.py
tests/test_config.py
tests/test_coordinator.py
tests/test_grpc.py
xain_fl/config/schema.py
xain_fl/coordinator/coordinator.py
xain_fl/coordinator/heartbeat.py
xain_fl/helloproto/numproto_server.py
xain_fl/logger.py
xain_fl/serve.py

https://xainag.atlassian.net/browse/PB-379
Decided to go with default setup for black formatter.
No
---

PB-379 Update black setup

---

.isort.cfg

Adjusted the line length of the isort config to match with the line length of black.
No
---

Adjust isort config

---

.github/workflows/development_pull_request.yml
.github/workflows/master_pull_request.yml
.isort.cfg
scripts/format.sh
scripts/test.sh

[PB-119](https://xainag.atlassian.net/browse/PB-119)
- update the `.isort.cfg` parameters
- update the calls to `isort`
- none
---

PB-119 consistify isort

---

CHANGELOG.md
setup.py
xain_fl/__version__.py

[PB-363](https://xainag.atlassian.net/browse/PB-363)
Prepare for release v0.4.0
No
---

PB-363 Update versions and changelog

---

setup.py

[PB-363](https://xainag.atlassian.net/browse/PB-363)
Hotfix for v0.4.0
No
---

Hotfix for v0.4.0

---

CHANGELOG.md
xain_fl/__version__.py

[PB-363](https://xainag.atlassian.net/browse/PB-363)
Start new development cycle: increase version , update changelog, announce upcoming features.
No
---

PB-363 Start new development cycle

---

.github/workflows/development_e2e_tests.yml
.github/workflows/development_pull_request.yml
.github/workflows/master_pull_request.yml
.github/workflows/master_tag.yml
.github/workflows/release_branch.yml

[DO-72](https://xainag.atlassian.net/browse/DO-72) [DO-47](https://xainag.atlassian.net/browse/DO-47)
CI builds test packages for release branches. Jobs are renamed to be consistent across all repos. 
GitHub Actions only parses the jobs present in the default branch, in our case, `master`, thus the need to merge to `master`
No
---

Hotfix: update ci

---

tests/test_coordinator.py
tests/test_grpc.py
xain_fl/coordinator/coordinator.py

- [PB-400](https://xainag.atlassian.net/browse/PB-400)
- increment the `epoch_base` by the number of `epochs` at the end of a successful training round
- none
---

PB-400 increment epoch base

---

docker-compose-dev.yml

[DO-78](https://xainag.atlassian.net/browse/DO-78)
This PR Adds grafana and an initial setup to consume Keycloak for authentication purposes.
No
A follow up PR may be necessary to finish the KeyCloak <-> Grafana integration, depending on complexity.
---

DO-78 :sparkles: add grafana

---

Dockerfile.dev

[DO-80](https://github.com/grpc/grpc/issues/21918)
Fix development Dockerfile (can't build gRPC due to https://github.com/grpc/grpc/issues/21918)
No
---

DO-80 :ambulance: fix dev dockerfile

---

Dockerfile
Dockerfile.dev
docker/entrypoint.sh

[DO-76](https://xainag.atlassian.net/browse/DO-76)
This PR changes the coordinator's development image
No
---

DO-76 :whale: non alpine image

---

CHANGELOG.md
setup.py

https://xainag.atlassian.net/browse/PB-417
Update changelog
No
---

PB-417 Update changelog and setup.py

---

.github/workflows/development_pull_request.yml
.github/workflows/master_pull_request.yml
CHANGELOG.md
Dockerfile
Dockerfile.dev
configs/example-config.toml
configs/xain-fl.toml
docker-compose-dev.yml
docker/entrypoint.sh
scripts/test.sh
setup.py
tests/conftest.py
tests/store.py
tests/test_config.py
tests/test_coordinator.py
tests/test_grpc.py
tests/test_metric_store.py
xain_fl/__main__.py
xain_fl/__version__.py
xain_fl/config/schema.py
xain_fl/coordinator/coordinator.py
xain_fl/coordinator/heartbeat.py
xain_fl/coordinator/metrics_store.py
xain_fl/coordinator/round.py
xain_fl/coordinator/store.py
xain_fl/fl/coordinator/aggregate.py
xain_fl/logger.py
xain_fl/serve.py

https://xainag.atlassian.net/browse/PB-417
Release v0.5.0
No
---

PB-417 :gem: Release v0.5.0

---

CHANGELOG.md
xain_fl/__version__.py

https://xainag.atlassian.net/browse/PB-417
Start new development cycle.
No
---

PB-417 Start new development cycle

---

.github/workflows/master_pr_push.yml
README.md

[PB-432](https://xainag.atlassian.net/browse/PB-432)
This PR updates the tests badge to a more accurate name, as well as pointing to the correct URL.
The CI is also updated to run lints and tests on push to master, to reflect this changes
No
---

Hotfix: PB-432 :pencil: :books: Update test badge and CI to reflect changes

---

mypy.ini
setup.py
xain_fl/__main__.py
xain_fl/config/schema.py
xain_fl/coordinator/coordinator.py
xain_fl/coordinator/metrics_store.py
xain_fl/coordinator/store.py
xain_fl/fl/coordinator/aggregate.py
xain_fl/fl/coordinator/controller.py
xain_fl/logger.py

https://xainag.atlassian.net/browse/PB-406
Configure Mypy, remove tests folder from mypy checks on CI
No
---

PB-406 Configure mypy

---

xain_fl/coordinator/round.py

[PB-423](https://xainag.atlassian.net/browse/PB-423)
The Coordinator is currently implemented with very little thread-safety. This leaves it prone to data races. This task is a starting point towards addressing this, focusing specifically on adding thread-safe access to the round-to-round state.
None, but see below.
A follow-up merge will address safety of other "session" state tracked by Coordinator.
---

PB-423 Round state thread-safety

---

README.md

- none
- add disclaimer
- none
---

HOTFIX add disclaimer

---

CHANGELOG.md
setup.py

[PB-445](https://xainag.atlassian.net/browse/PB-445)
* Updated Changelog
* Changed xain-sdk and cain-proto version to 0.6.0
No
---

PB-445 Update Changelog

---

CHANGELOG.md
README.md
configs/example-config.toml
configs/xain-fl.toml
docker-compose-dev.yml
docs/network_architecture.rst
mypy.ini
setup.py
tests/conftest.py
tests/store.py
tests/test_config.py
tests/test_coordinator.py
tests/test_grpc.py
tests/test_metric_store.py
xain_fl/__main__.py
xain_fl/__version__.py
xain_fl/config/schema.py
xain_fl/coordinator/__init__.py
xain_fl/coordinator/coordinator.py
xain_fl/coordinator/metrics_store.py
xain_fl/coordinator/participants.py
xain_fl/coordinator/round.py
xain_fl/coordinator/store.py
xain_fl/fl/coordinator/aggregate.py
xain_fl/fl/coordinator/controller.py
xain_fl/logger.py
xain_fl/serve.py

[PB-445](https://xainag.atlassian.net/browse/PB-445)
* Release of 0.6.0
No
---

PB-445 :gem: Release v0.6.0

---

CHANGELOG.md
xain_fl/__version__.py

[PB-445](https://xainag.atlassian.net/browse/PB-445)
* Updated version and changelog
No
---

PB-445 Start new development cycle

---

rust/src/coordinator/core/protocol.rs

This helps for debugging. Here is what the logs looks like:
```
2020-03-23T15:51:53.506506461+00:00  DEBUG root:service: xain_fl::coordinator::core::service: handling end training request                                                                   
2020-03-23T15:51:53.506593030+00:00   INFO root:service: xain_fl::coordinator::core::protocol: end training request: 0c249283-1049-40a1-abb6-1f6b00fa2d80(Selected) (success=true)            
2020-03-23T15:51:53.506674660+00:00   INFO root:service: xain_fl::coordinator::core::protocol: round complete, resetting the clients counters=Counters(waiting=0 selected=0 done=100 done_and_
inactive=0 ignored=0) …
```

dump the protocol's counters in the logs

---

docker/docker-compose.yml
rust/src/aggregator/api.rs
rust/src/coordinator/api.rs
swagger/aggregator.yml
swagger/coordinator.yml

**References**
[PB-569](https://xainag.atlassian.net/browse/PB-569)
**Summary**
- added swagger files that describes the current API for the coordinator as well the aggregator
- added swagger ui in docker compose file
**Open tasks**
- create script that updates the versions within the swagger files

PB-519 Add swagger files

---

rust/src/pet/message/mod.rs
rust/src/pet/message/round.rs
rust/src/pet/message/sum.rs
rust/src/pet/message/sum2.rs
rust/src/pet/message/update.rs

**References**
- [PB-590](https://xainag.atlassian.net/browse/PB-590)
**Summary**
- add tests for the message buffers
- add tests for the message boxes
- add tests for the messages

PB-590 update tests

---

rust/src/tests/coordinator.rs

**References:**
- [PB-571](https://xainag.atlassian.net/browse/PB-571)
**Summary:**
- added first dropout test

PB-571 First dropout test

---

rust/src/aggregator/api.rs

This is  follow-up of https://github.com/xainag/xain-fl/pull/360
The API now return proper JSON formatted errors :)

PB-598: aggregator api error handling

---

scripts/bump_version.sh

- do not tag the repo, this should be done manually
- color the output
- add an attempt to publish the packages to test.pypi.org

Release script improvements

---

rust/rustfmt.toml
rust/src/aggregator/rpc.rs
rust/src/coordinator/api.rs
rust/src/pet/coordinator.rs
rust/src/pet/message/mod.rs
rust/src/pet/message/update.rs
rust/src/pet/participant.rs
rust/src/pet/utils.rs

**References**
- [PB-602](https://xainag.atlassian.net/browse/PB-602)
**Summary**
- add tests for participant message dictionaries
- add tests for coordinator round dictionaries
- add tests for coordinator round parameters
- add tests for coordinator round phase transitions

PB-602 pet functionality tests

---

rust/src/coordinator.rs
rust/src/lib.rs
rust/src/message/mod.rs
rust/src/message/sum2.rs
rust/src/participant.rs
rust/src/service.rs

Each commit can be reviewed separately. The main change is 3ea765f.
I'd like to _maybe_ refactor further at some point, taking inspiration from this blog post https://hoverbear.org/blog/rust-state-machine-pattern/

Coordinator refactoring

---

rust/rustfmt.toml
rust/src/coordinator.rs
rust/src/message/sum.rs
rust/src/message/sum2.rs
rust/src/message/update.rs
rust/src/participant.rs

**Summary**
- set `imports_layout = "HorizontalVertical"` for `rustfmt` and reformat imports

rustfmt import layouts

---

k8s/aggregator/development/ingress.yaml
k8s/coordinator/development/ingress.yaml

DO-96 :rocket: Add SSL in cluster

---

.github/workflows/rust.yml
rust/Cargo.lock
rust/Cargo.toml

there are tons of unused dependencies that slow compilation down.

cleanup dependencies

---

.github/workflows/rust.yml
.github/workflows/rust_release.yaml

This PR builds a Dockerfile and Docker.release (on semver tag pushes) in the CI and pushed them to Docker Hub

DO-106 :sparkles: :whale: Build and push docker images in CI

---

docker/docker-compose.yml

**References**
- [PB-724](https://xainag.atlassian.net/browse/PB-724)
**Summary**
- added redis to docker-compose file

PB-724 Add redis

---

rust/src/coordinator.rs
rust/src/mask/masking.rs

This was removed by mistake in
https://github.com/xainag/xain-fl/pull/398

re-add unmasking logic

---

rust/src/sdk/api.rs

The definitions of C types are quite vague, therefore this uses `c_ulonglong` instead of `c_ulong` to allow for safe casts from Rust's `usize`.

PB-774 fix C types in API

---

k8s/coordinator/base/deployment.yaml
k8s/coordinator/base/kustomization.yaml
k8s/coordinator/base/service.yaml
k8s/coordinator/development/config-volume-mount.yaml
k8s/coordinator/development/config.toml
k8s/coordinator/development/history-limit.yaml
k8s/coordinator/development/ingress.yaml
k8s/coordinator/development/kustomization.yaml

This is needed in preparation for both [PB-838](https://xainag.atlassian.net/browse/PB-838) and [PB-839](https://xainag.atlassian.net/browse/PB-839).

PB-822 Merge k8s folder from `master` to `pet` branch

---

configs/config.toml
configs/docker-dev.toml
configs/docker-release.toml
docker/docker-compose.yml
k8s/coordinator/base/deployment.yaml
k8s/coordinator/development/config.toml
rust/src/bin/main.rs
rust/src/settings.rs

Summary:
- adds the possibility to define `logging`in the config file

Add logging settings

---

rust/src/services/fetchers/mask_length.rs
rust/src/services/fetchers/mod.rs
rust/src/services/fetchers/model.rs
rust/src/services/fetchers/round_parameters.rs
rust/src/services/fetchers/scalar.rs
rust/src/services/fetchers/seed_dict.rs
rust/src/services/fetchers/sum_dict.rs
rust/src/services/messages/message_parser.rs
rust/src/services/messages/mod.rs
rust/src/services/messages/pre_processor/mod.rs
rust/src/services/messages/pre_processor/sum.rs
rust/src/services/messages/pre_processor/sum2.rs
rust/src/services/messages/pre_processor/update.rs
rust/src/services/messages/state_machine.rs
rust/src/services/mod.rs

Documentation for https://github.com/xainag/xain-fl/pull/421

Document `crates::services`

---

rust/src/lib.rs

**References**
- [PB-877](https://xainag.atlassian.net/browse/PB-877)
**Summary**
- add the intro text from the getting started page
links to the getting started readme and the homepage need to be added later once they are updated.

PB-877 document crate root

---

rust/src/client/mod.rs
rust/src/sdk/api.rs

**References**
- [PB-846](https://xainag.atlassian.net/browse/PB-846)
**Summary**
- add a url input to the ffi client constructor
- move the flag which indicates a new round to the ffi client (`has_new_coord_pk_since_last_check`) to the end of the client round loop for atomic behavior

PB-846 add url input to ffi client

---

rust/src/lib.rs
rust/src/mask/config/mod.rs
rust/src/settings.rs

**References**
- [PB-876](https://xainag.atlassian.net/browse/PB-876)
**Summary**
- update settings documentation
- fix `lib.rs` intro text typos (as pointed out in #446 for the readme)

PB-876 document settings

---

rust/src/rest.rs

addresses review comment from #448

adjust docstring for HTTP API

---

README.md
rust/Cargo.lock
rust/Cargo.toml
rust/src/bin/main.rs
rust/src/bin/test-drive-net.rs
rust/src/bin/test-drive.rs
rust/src/crypto/mod.rs
rust/src/mask/mod.rs
rust/src/message/buffer.rs
rust/src/message/payload/sum.rs
rust/src/message/traits.rs
rust/src/sdk/api.rs
rust/src/settings.rs

```
s/xain\.io/xayn\.dev/g
s/xainag/xaynetwork/g
s/xain[-|_]fl/xaynet/g
```

PB-913 Check and adjust documentation for xaynet

---

configs/config.toml
configs/docker-dev.toml
configs/docker-release.toml
k8s/coordinator/development/config.toml
rust/src/bin/main.rs
rust/src/client/participant.rs
rust/src/mask/masking.rs
rust/src/mask/mod.rs
rust/src/settings.rs
rust/src/state_machine/coordinator.rs
rust/src/state_machine/mod.rs
rust/src/state_machine/phases/sum.rs
rust/src/state_machine/phases/sum2.rs
rust/src/state_machine/phases/update.rs
rust/src/state_machine/tests/builder.rs
rust/src/state_machine/tests/mod.rs

**Summary**
- makes the model size value configurable
- adds `ModelSettings` to `Settings`
- fixes missing fields in the config

Add model size configuration

---

.github/workflows/dockerhub-master.yml

The final battle! :upside_down_face:

PB-925 Clean-up of stale ReplicaSets of development namespace

---

rust/src/client/mobile_client/client.rs
rust/src/client/request.rs
rust/src/rest.rs
rust/src/services/fetchers/mask_length.rs
rust/src/services/fetchers/mod.rs
rust/src/services/fetchers/model.rs
rust/src/services/fetchers/round_parameters.rs
rust/src/services/fetchers/scalar.rs
rust/src/services/fetchers/seed_dict.rs
rust/src/services/fetchers/sum_dict.rs
rust/src/services/messages/mod.rs
rust/src/services/mod.rs
rust/src/services/utils.rs

Possible future improvements:
- some of the code could easily be generated with macros
- we should start tracing the requests in the rest layer

trace the fetcher services requests

---

README.md
rust/xaynet-server/src/services/messages/state_machine.rs

Check documentation after cargo workspace split

---

rust/xaynet-server/src/examples.rs
rust/xaynet-server/src/settings.rs

Ref: https://github.com/xaynetwork/xaynet/pull/518

Remove "expected_participants" in docs

---

rust/xaynet-core/src/mask/config/serialization.rs
rust/xaynet-core/src/mask/object/serialization.rs
rust/xaynet-core/src/message/message.rs
rust/xaynet-core/src/message/mod.rs
rust/xaynet-core/src/message/payload/chunk.rs
rust/xaynet-core/src/message/payload/sum.rs
rust/xaynet-core/src/message/payload/sum2.rs
rust/xaynet-core/src/message/payload/update.rs
rust/xaynet-core/src/message/traits.rs
rust/xaynet-core/src/message/utils/chunkable_iterator.rs
rust/xaynet-core/src/message/utils/mod.rs
rust/xaynet-server/src/services/messages/message_parser.rs
rust/xaynet-server/src/services/messages/multipart/buffer.rs
rust/xaynet-server/src/services/messages/multipart/service.rs

- rename `FromBytes::from_bytes` into `FromBytes::from_byte_slice`
- add `FromBytes::from_byte_stream`
- add a chunkable iterator under `xaynet_core::messages::utils`, that is used internally

Implement message parsing from byte streams

---

rust/xaynet-client/src/lib.rs
rust/xaynet-client/src/utils/mod.rs
rust/xaynet-client/src/utils/multipart/chunker.rs
rust/xaynet-client/src/utils/multipart/mod.rs

I decided to split my PR into smaller chunks. This is the module that implements the logic for splitting messages in chunks.

message splitting logic

---

.github/workflows/dockercompose-validation.yml
.github/workflows/dockerfile-validation.yml

Adjust steps names

---

rust/xaynet-server/src/state_machine/phases/sum2.rs
rust/xaynet-server/src/storage/impls.rs
rust/xaynet-server/src/storage/redis.rs
rust/xaynet-server/src/storage/tests/mod.rs

**Summary**
- prepares the Redis client for storing mask dict 
- added lua script for increment mask count
- added PET errors for the increment mask count operation
- fixed/added tests

Redis mask dict preparation

---

rust/xaynet-core/src/mask/model.rs

This seems to be a new clippy lint

fix unnecessary_lazy_evaluations clippy warnings

---

.github/workflows/rust.yml
rust/Cargo.lock
rust/xaynet-core/Cargo.toml
rust/xaynet-core/benches/messages.rs

This adds a benchmark for the sum messages serialization/deserialization.
The results are not super consistent but I'm running the benchmarks on a laptop with a firefox full of tabs and extensions, teams, docker, and various other services.
We'll probably have to tweak these benchmarks later anyway.

add first benchmark

---

configs/config.toml
configs/docker-dev.toml
k8s/coordinator/base/deployment.yaml
k8s/coordinator/development/config.toml
rust/Cargo.lock
rust/xaynet-server/Cargo.toml
rust/xaynet-server/src/bin/main.rs
rust/xaynet-server/src/settings.rs

**Summary**
- added S3 settings

S3 settings

---

rust/Cargo.lock
rust/xaynet-server/Cargo.toml
rust/xaynet-server/src/storage/impls.rs

small follow up PR based on https://github.com/xaynetwork/xaynet/pull/538#discussion_r500269333

Bind error codes to error variants

---

.github/workflows/rust.yml

- Adds `--all-targets` flag to `cargo check` and `cargo test`
- Adds a separate command that runs `cargo check` and `cargo test` with `--all-features` flag

Add --all-targets / --all-features flag

---

.github/workflows/dockerhub-pr-with-parameters.yml

Add the option of when you add a comment using: 
```/build_pr args```
It will trigger the build of the container and deploy it to k8s

XN-1209 allow the deployment of a pr on dev k8s using /build_pr args

---

.github/workflows/dockerhub-pr-with-parameters.yml

We tested with permission level of maintain but it seems do not have enough permission, so we are changing to write permission

XN-1209 Change permission level from maintain to write

---

rust/xaynet-server/src/services/messages/error.rs
rust/xaynet-server/src/services/messages/mod.rs
rust/xaynet-server/src/services/messages/multipart/mod.rs

We had implemented the service for handling multipart messages, but never actually called it.

call the multipart handler in xaynet-server

---

rust/xaynet-server/src/state_machine/mod.rs
rust/xaynet-server/src/state_machine/phases/error.rs
rust/xaynet-server/src/state_machine/phases/unmask.rs
rust/xaynet-server/src/state_machine/tests/initializer.rs
rust/xaynet-server/src/state_machine/tests/mod.rs
rust/xaynet-server/src/storage/s3.rs

**Summary**
- impls `ModelStorage` for s3 client
- refactored s3 client errors

Impl ModelStorage for s3 client

---

configs/config.toml
configs/docker-dev.toml
rust/Cargo.lock
rust/xaynet-server/src/rest.rs
rust/xaynet-server/src/settings/mod.rs
rust/xaynet-server/src/settings/tests/mod.rs

**Summary**
The warp guys seem to like our merge request in general, but they requested some name changes. This pr applies those changes in the fork to our server.

Apply updates from warp fork changes

---

rust/xaynet-server/src/state_machine/initializer.rs
rust/xaynet-server/src/state_machine/mod.rs
rust/xaynet-server/src/state_machine/tests/builder.rs
rust/xaynet-server/src/state_machine/tests/initializer.rs

addresses the comment: https://github.com/xaynetwork/xaynet/pull/604#discussion_r525022050

separate state machine initializer

---

k8s/coordinator/base/deployment.yaml

XN-1515 Define k8s deployment strategy to avoid coexisting instances of the coordinator

---

CHANGELOG.md

[rendered version](https://github.com/xaynetwork/xaynet/blob/format-changelog/CHANGELOG.md)

format current changelog

---

CHANGELOG.md

[rendered version](https://github.com/xaynetwork/xaynet/blob/update-changelog/CHANGELOG.md)

Add unreleased changes 

---

bindings/python/README.md

[rendered version](https://github.com/xaynetwork/xaynet/blob/add-pypi-setup/bindings/python/README.md)

add setup via pip

---

rust/xaynet-analytics/src/data_combination/data_points/screen_active_time.rs
rust/xaynet-analytics/src/data_combination/data_points/screen_enter_count.rs
rust/xaynet-analytics/src/data_combination/data_points/was_active_each_past_period.rs
rust/xaynet-analytics/src/data_combination/data_points/was_active_past_n_days.rs

Refers to: [XN-1542](https://xainag.atlassian.net/browse/XN-1542)

add data points unit tests

---

CHANGELOG.md
rust/xaynet-server/src/examples.rs

The links on the release page have also been updated

update whitepaper link

---

CHANGELOG.md
rust/Cargo.lock
rust/examples/Cargo.toml
rust/examples/test-drive/participant.rs
rust/xaynet-mobile/Cargo.toml
rust/xaynet-mobile/src/participant.rs
rust/xaynet-sdk/Cargo.toml
rust/xaynet-sdk/src/lib.rs
rust/xaynet-sdk/src/utils/concurrent_futures.rs

- checked C tests in `xaynet-mobile`
- checked python bindings
- checked test-drive

upgrade tokio in xaynet sdk/mobile/examples

---

rust/Cargo.lock
rust/xaynet-analytics/Cargo.toml
rust/xaynet-analytics/src/database/analytics_event/data_model.rs
rust/xaynet-analytics/src/database/analytics_event/repo.rs
rust/xaynet-analytics/src/database/common.rs
rust/xaynet-analytics/src/database/isar.rs

[XN-1611](https://xainag.atlassian.net/browse/XN-1611)
For the [ScreenRoute PR](https://github.com/xaynetwork/xaynet/pull/704) we need some new changes that were implemented since we last integrated Isar (and git referenced a specific commit), so this PR is to upgrade to the latest commit, and unblock the other PR.

upgrade to latest isar

---

rust/xaynet-analytics/src/data_combination/data_combiner.rs
rust/xaynet-analytics/src/data_combination/data_points/data_point.rs
rust/xaynet-analytics/src/data_combination/data_points/screen_active_time.rs
rust/xaynet-analytics/src/data_combination/data_points/screen_enter_count.rs
rust/xaynet-analytics/src/data_combination/data_points/was_active_each_past_period.rs
rust/xaynet-analytics/src/data_combination/data_points/was_active_past_n_days.rs
rust/xaynet-analytics/src/database/analytics_event/data_model.rs
rust/xaynet-analytics/src/database/analytics_event/repo.rs
rust/xaynet-analytics/src/database/common.rs
rust/xaynet-analytics/src/database/isar.rs
rust/xaynet-analytics/src/database/mod.rs
rust/xaynet-analytics/src/database/screen_route/data_model.rs
rust/xaynet-analytics/src/database/screen_route/mod.rs
rust/xaynet-analytics/src/database/screen_route/repo.rs

[XN-1520](https://xainag.atlassian.net/browse/XN-1520)
This PR adds the ScreenRoute struct with its IsarAdapter and Repo implementations. I have also added a lifetime to AnalyticsEvent.

add screen route data model and repo

---

.github/workflows/rust.yml
bindings/python/Cargo.lock
bindings/python/Cargo.toml
bindings/python/README.md
bindings/python/examples/keras_house_prices/setup.py

updates
- numpy #705 
- pandas #727 
- pyo3 #726 
- maturin

update python dependencies

---

k8s/coordinator/development/history-limit.yaml

As documented here: https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy

Update k8s deployment configuration for quicker GC on dev env

---

bindings/python/Cargo.lock
bindings/python/Cargo.toml
rust/Cargo.lock
rust/examples/Cargo.toml
rust/xaynet-core/Cargo.toml
rust/xaynet-mobile/Cargo.toml
rust/xaynet-sdk/Cargo.toml
rust/xaynet-server/Cargo.toml

Rollup of:
- #737
- #738 
- #741 
- #742 
- #743 
- #744
- #745
- #748
- #750
- #752
- #754
- #755
- #757

Rollup bump version of dependencies 

---

rust/Cargo.lock
rust/xaynet-analytics/Cargo.toml
rust/xaynet-analytics/src/controller.rs
rust/xaynet-analytics/src/database/analytics_event/adapter.rs
rust/xaynet-analytics/src/database/analytics_event/data_model.rs
rust/xaynet-analytics/src/database/analytics_event/repo.rs
rust/xaynet-analytics/src/database/common.rs
rust/xaynet-analytics/src/database/controller_data/adapter.rs
rust/xaynet-analytics/src/database/controller_data/data_model.rs
rust/xaynet-analytics/src/database/controller_data/repo.rs
rust/xaynet-analytics/src/database/isar.rs
rust/xaynet-analytics/src/database/screen_route/adapter.rs
rust/xaynet-analytics/src/database/screen_route/data_model.rs
rust/xaynet-analytics/src/database/screen_route/repo.rs

[XN-1560](https://xainag.atlassian.net/browse/XN-1560)
Adds unit tests for the data models and the `AnalyticsController`. 
Those for the latter also double down as integration tests.
It also fixes a few bugs and upgrades to a newer version of Isar (still a git ref).
(Heads up: in my case Github collapsed the file where the `AnalyticsController` is cause the diff is big, but yeh, that's where most of the changes are)

add analytics controller tests

---

rust/xaynet-analytics/src/controller.rs
rust/xaynet-analytics/src/data_combination/data_combiner.rs
rust/xaynet-analytics/src/data_combination/data_points/data_point.rs
rust/xaynet-analytics/src/database/analytics_event/adapter.rs
rust/xaynet-analytics/src/database/analytics_event/data_model.rs
rust/xaynet-analytics/src/database/analytics_event/repo.rs
rust/xaynet-analytics/src/database/common.rs
rust/xaynet-analytics/src/database/controller_data/adapter.rs
rust/xaynet-analytics/src/database/controller_data/data_model.rs
rust/xaynet-analytics/src/database/controller_data/repo.rs
rust/xaynet-analytics/src/database/isar.rs
rust/xaynet-analytics/src/database/screen_route/adapter.rs
rust/xaynet-analytics/src/database/screen_route/data_model.rs
rust/xaynet-analytics/src/database/screen_route/repo.rs
rust/xaynet-analytics/src/sender.rs

[XN-1680](https://xainag.atlassian.net/browse/XN-1680)
Add documentation to Federated Analytics crate.
Please let me know if it's clear enough.

add analytics documentation

---

.github/workflows/dockerhub-cleanup.yml

DEVOPS-22 Hotfix: covers the case of when there's nothing to be deleted
