- scripts/test.sh
- xain/benchmark/net/blog_cnn_test.py
- xain/benchmark/net/orig_2nn_test.py
- xain/benchmark/net/orig_cnn_test.py
- xain/benchmark/net/resnet_test.py
- xain/ops/results_test.py
Also don't split the run of integration and unit tests in tests.sh script as it increases CI duration
> Mark tests which take >1s as slow

- .circleci/config.yml
- .clang-format
- protobuf/xain/grpc/hellonumproto.proto
- scripts/format.sh
- scripts/test.sh
This pr depends on #28 
- added .clang-format with settings to format proto files
- updated `scripts/format.sh` to also format proto files
- updated `scripts/test.sh` to check the format of proto files
- updated the CI config to install clang-format.
After this is merged `clang-format` will be a development requirement.
> Use clang-format to format proto files

- scripts/test.sh
Small fix so that an error exit code of clang-format is detected by the CI
> fix clang-format CI invocation to output correct exit code

- .circleci/config.yml
- README.md
- protobuf/xain/grpc/hellonumproto.proto
This pr fixes a problem with `clang-format` where there was a difference in how files are formatted that was introduced with `clang-format v8.0.0`.
- update the CI to use clang-format v8+. This required us to use the ubuntu 18.04 docker image to run the `tests` job since we need both an up to date version of clang and python3.7
> Require clang-format v8+

- xain/benchmark/benchmark.py
This MR fixes the naming of the cpp-fashion-mnist-100p benchmark by changing `federated...` to `unitary...` and vise versa.
> fixing naming for tasks of benchmark cpp-fashion-mnist-100p

- CODEOWNERS
Making code ownership more specific to get better reviewers recommendations. @r-marques @skade @danieljanes @stjepang can you please acknowledge if I got it right? Especially on the rust side we will need to adjust it later on in subsequent PR I think. As soon as code goes into master.
> Make code owner responsibilities more specific

- xain/ops/run.py
We actually would like to use the m5.large up to m5.24xlarge but AWS is not easily willing to give us the increase without asking again and again and again for limit increases. Therefore we are switching to using c4 which have higher default limits.
> Adjust used instance types to instances with limit >=50

- controller/src/aggregation.rs
We started to deny warnings before #69 was merged, but this sneaked-in.
> Fix build of rust code

- xain/benchmark/aggregation/final_task_accuracies.py
- xain/benchmark/aggregation/final_task_accuracies_test.py
- xain/benchmark/aggregation/plot.py
- xain/benchmark/aggregation/task_accuracies.py
- xain/benchmark/aggregation/task_accuracies_test.py
- xain/generator/partition_volume_distributions.py
- xain/helpers/storage.py
- xain/helpers/storage_test.py
To enable multiple aggregates in a clean way in the output directory will now contain a sub-directory for each group for which the aggregate function is called
> Add subdirectories for aggregates

- xain/benchmark/bench_cl.py
- xain/benchmark/bench_ea.py
- xain/benchmark/exec/__main__.py
- xain/benchmark/exec/run.py
- xain/fl/coordinator/coordinator.py
- xain/fl/participant/participant.py
- xain/fl/participant/participant_test.py
Next to updated model parameters and metrics, the participants now also return the optimizer state (containing e.g. the learning rate).
Note that the return types start to get quite complex. I've created a follow-up task (XP-102) to refactor this and unify some of those types into a single type. The reason I haven't refactored it already is twofold:
1. To keep the scope of this PR reasonable
2. To not break aggregation code which relies on the current `results.json` file structure
> Collect and report optimizer state from each selected participant

- scripts/ls_running_instances.sh
This script only captures @tanertopal 's single-line statement to list running AWS instances in an attempt to make it easier to access for everyone.
> Create standalone script to list running AWS instances

- xain/benchmark/aggregation/aggregation.py
- xain/benchmark/aggregation/conftest.py
- xain/benchmark/aggregation/final_task_accuracies.py
- xain/benchmark/aggregation/learning_rate.py
- xain/benchmark/aggregation/learning_rate_test.py
- xain/benchmark/aggregation/plot.py
- xain/benchmark/aggregation/results.py
- xain/benchmark/aggregation/results_test.py
- xain/benchmark/aggregation/task_accuracies.py
Adds a new aggregate method which will for all federated learning tasks which contain a history of optimizer configurations plot the learning rates as an additional plot with one curve per federated task.
Unitary tasks will be ignored as they do not contain the optimizer configuration.
> Learning rate aggregation

- xain/benchmark/aggregation/learning_rate.py
The learning rate plot now starts at index 1.
> Fix off-by-one error in learning rate plot

- RELEASE_PROCESS.md
This merge request adds an initial version of a `RELEASE_PROCESS.md` document that documents:
- Our versioning schema
- How we handle releases in the git history
- Instructions and naming conventions on how to create a release on Github
- Instructions on how to build and publish a python package to PyPi
> Document the release process

- README.md
- docs/Makefile
- docs/conf.py
- docs/index.rst
- docs/make.bat
- setup.py
- Added new `docs` extra to setup.py to hold all documentation related
dependencies.
- Updated README with instructions on how to build the documentation
Note that all files currently under `docs/` are auto generated by sphinx
> Initial support for sphinx documentation

- docs/conf.py
- scripts/test.sh
The goal of this pr is to have the CI check if the documentation builds without warnings.
Since this is a simple check I decided to just add an extra check in `scripts/test.sh`.
Once we integrate with readthedocs we may consider having a separate job for the documentation.
> CI support for documentation

- rust/Cargo.lock
- rust/xain-coordinator/Cargo.toml
- rust/xain-coordinator/src/lib.rs
- rust/xain-coordinator/src/training.rs
This implements the scaffold for the Coordinator protocol. It is implemented as an explicit state machine (in contrast to Python implementation, which constructs a state machine implicitly on the stack, by blocking). It is not bound to any particular transport, and so should be testable in isolation. 
I this is a WIP, as I want to tweak the representation a bit, to make happy path more clear. 
I am also not sure what the actual protocol do we want here: currently it's just:
* clients send join to coordinator
* for n rounds
* coordinator broadcasts model to clients
* clients send updated models to the coordinator
> implement coordinator's state machine scaffold

- .circleci/config.yml
This fixes the CI currently broken on master.
- Updated CI configuration so that cmake is available for rust tests
- Added golang which is a requirement of boringssl
> Rust tests require cmake to be installed

- .circleci/config.yml
- .gitignore
- README.md
- docs/Makefile
- docs/conf.py
- docs/index.rst
- docs/install.md
- scripts/test.sh
- xain/benchmark/aggregation/final_task_accuracies.py
- xain/benchmark/aggregation/learning_rate.py
- xain/benchmark/aggregation/task_accuracies.py
- xain/benchmark/net/resnet.py
- xain/generator/data.py
Depends on #112 
- Configured sphinx to be able to generate documentation from docstrings.
- Fixed some bad formatting in some docstrings
The instructions to build the docs also changed since we also need to generate the documentation from the docstrings. This is done with a new make target:
```bash
$ cd docs/
$ make docs
```
> Add code documentation to sphinx

- docs/quick.md
This merge request updates the benchmark instructions so that we can run training sessions locally without the need to set aws credentials.
> Update benchmark documentation

- README.md
Since the documentation moved under `docs/` added a link in README to the bechmarking documentation.
> Added a link to the benchmarks documentation

- docs/conf.py
- protobuf/xain/grpc/coordinator.proto
- xain/grpc/conftest.py
- xain/grpc/coordinator.py
- xain/grpc/test_coordinator_logic.py
- xain/grpc/test_grpc.py
This is still a work in progress but the main goal is to have the coordinator logic independent of gRPC. This makes it easier to unit tests the coordinator logic and makes it easier to use without gRPC.
The coordinator logic is basically just one method that implements a state machine that reacts to gRPC messages passed to it. This messages can be used both over gRPC or locally without networking.
- Added [intersphinx](http://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html) to link to external documentation
> Add coordinator logic

- xain/grpc/coordinator.py
- xain/grpc/test_coordinator_logic.py
- xain/grpc/test_grpc.py
This should **ONLY** be reviewed once #128 is merged.
This merge request adds checks to the participant identity as provided by the grpc context before accepting any requests.
Currently it does the following checks:
- It only accepts requests for participants that have already rendezvous
- It prevents a participant from sending multiple updates in the same round
The `Coordinator` class raises custom exceptions if any of the above conditions happen and the gRPC servicer returns grpc errors back to participant with a description in case any of the above condition happen.
> Checks participants identity

- setup.py
- xain/grpc/coordinator.py
- xain/logger.py
This should ONLY be reviewed once #138  is merged.
- Configured a project level logger. To get a logger use `xain.logger.get_logger`.
- Updated the version of `absl-py`. The current version took aggressive control of the root logger making it very difficult to configure our own logging. See https://github.com/abseil/abseil-py/issues/99
- Replaced print statements on the coordinator with logging
> Add logging to coordinator

- .gitignore
- docs/Makefile
- docs/index.rst
With this pr the sphinx documentation will have two sections under _API Documentation_:
- _Code Reference XAIN_
- _Code Reference Benchmarks_
> Updated sphinx to also document the benchmarks package

- xain/grpc/coordinator.py
- xain/grpc/test_coordinator_logic.py
- xain/grpc/test_grpc.py
This should ONLY be reviewed once #139 is merged.
The coordinator is now aware of participants that disconnect and reacts to it by transition to the STANDBY state if the the current number of participants falls bellow `required_participants`.
Also renamed some references of `peer` to `participant` for more consistent terminology.
> Handle failing participants

- xain/grpc/coordinator.py
- xain/grpc/test_coordinator_logic.py
- xain/grpc/test_grpc.py
This should ONLY be reviewed once #141 is merged.
- deny StartTraining requests from participants if the coordinator is not in the ROUND state.
- small refactor to split the method that handles client requests.
- added grpc error handling for the invalid requests
- added tests
> Check state transitions

- protobuf/xain_fl/grpc/coordinator.proto
- xain_fl/grpc/coordinator_pb2.py
- xain_fl/grpc/coordinator_pb2_grpc.py
[XAIN-284 Ensure all grpc proto files have the same package name](https://xainag.atlassian.net/browse/XP-284)
Fixed the issue that the SDK participant and the FL coordinator couldn't communicate via gRPC.
No
---
> XAIN-284  Ensure all grpc proto files have the same package name

- README.md
[XP-385 Fix the documentation badge in xain-fl](https://xainag.atlassian.net/browse/XP-385)
* fixed badge link
No
---
> XP-336 Fix docs badge

- tests/controller_test.py
- xain_fl/coordinator/coordinator.py
- xain_fl/fl/coordinator/controller.py
[XP-357](https://xainag.atlassian.net/browse/XP-357)
Corrects the initial implementation of Participant selection by initialising the Controller only once and then passing the participant_ids only when calling `select_ids` on the controller.
None
---
> XP-357 make controller parametrisable

- docker-compose-dev.yml
[DO-49](https://xainag.atlassian.net/browse/DO-49)
This PR provisions two initial buckets for minio in the dev environment. One for temporary weights from participants, and one for storage of aggregated models
No. [With the research done](https://github.com/minio/mc/issues/2497) by @Robert-Steiner  it was confirmed that a timing issue is present thus the timeout was increased to 5 secs 
---
> DO-49 default buckets minio

- setup.py
- tests/test_grpc.py
[XP-373](https://xainag.atlassian.net/browse/XP-373)
Add link to SDK repo inside `setup.py` and reactivates the tests that were disabled both by the comments and by the `@pytest.mark.skip` decorator.
I had to refactor a bit `test_end_training` test. The refactor addresses two things:
1. renaming variables to make them more readable
2. i changed `np.testing.assert_allclose` to `np.testing.assert_equal` because it was failing with a numpy error. 
**My guess** is that since this test has been skipped for a while, the fact that in the meantime we changed numpy version affected this test. So had this test not been skipped when the numpy version was changed, it would have been picked up back then (just a guess on the reason now it was failing, not a blame). The slight change i made to the test …
> Xp 373 add sdk as dependency in fl

- tests/conftest.py
- tests/test_grpc.py
[XP-119 Fix gRPC testing setup so that it can run on macos](https://xainag.atlassian.net/browse/XP-119)
* close channel after each test
No
---
> XP-119 Fix gRPC testing setup so that it can run on macOS

- setup.py
- tests/test_grpc.py
- xain_fl/coordinator/coordinator.py
- xain_fl/coordinator/round.py
- [XP-422](https://xainag.atlassian.net/browse/XP-422)
- update the coordinator state machine to use the new ai metrics object
- fix mocking destinations for the tests
- note that these changes are interdependent with the merge requests of [xain-sdk](https://github.com/xainag/xain-sdk/pull/28) and [xain-proto](https://github.com/xainag/xain-proto/pull/3) and need to be merged simultaneously to avoid breaking stuff
---
> XP-422 ai metrics

- .github/workflows/development.yml
- .github/workflows/master.yml
- Dockerfile
- Dockerfile.dev
- docker-compose-dev.yml
- scripts/format.sh
- scripts/test.sh
- setup.py
- tests/conftest.py
- tests/port_forwarding.py
- tests/store.py
- tests/test_grpc.py
- xain_fl/cli.py
- xain_fl/coordinator/coordinator.py
- xain_fl/coordinator/coordinator_grpc.py
- xain_fl/coordinator/store.py
- xain_fl/serve.py
https://xainag.atlassian.net/browse/XP-40
https://xainag.atlassian.net/browse/XP-308
https://xainag.atlassian.net/browse/XP-309
https://xainag.atlassian.net/browse/XP-311
This commits adds a new module `xain-fl.coordinator.store`, which
contains a `Store()` class that can read from and write to S3
buckets. At the end of each round, the aggregated weights are uploaded
to an S3 bucket. Note that as a first step, the aggregated weights are
still sent to the participants via gRPC.
We're trying to not have IO related code in the Coordinator class, so
the Store instance is held by the CoordinatorGrpc instead of
Coordinator. However, since the Coordinator is currently generating
the grpc messages, which are inherently coupled to the IO logic. This
means that if at some point the messages need to …
> XP-308: store aggregated weights in S3 buckets

- .github/workflows/development.yml
- .github/workflows/master.yml
- Dockerfile
- Dockerfile.dev
- docker-compose-dev.yml
- scripts/format.sh
- scripts/test.sh
- setup.py
- tests/conftest.py
- tests/port_forwarding.py
- tests/store.py
- tests/test_grpc.py
- xain_fl/cli.py
- xain_fl/coordinator/coordinator.py
- xain_fl/coordinator/coordinator_grpc.py
- xain_fl/coordinator/store.py
- xain_fl/fl/coordinator/aggregate.py
- xain_fl/fl/coordinator/controller.py
- xain_fl/serve.py
- [XP-436](https://xainag.atlassian.net/browse/XP-436)
This bug appears to have been introduced as part of [Participant selection](https://github.com/xainag/xain-fl/pull/179) whereby the Coordinator no longer advertises the `FINISHED` state when the whole training session is over. This is in turn a problem for Participants: they end up waiting indefinitely (in the `POST_TRAINING` state), unable to terminate. The bug was discovered as part of [XP-208](https://xainag.atlassian.net/browse/XP-208) which was previously blocked by this.
In a little more detail, this PR:
1. rectifies the above bug so that `FINISHED` states are indeed advertised.
2. adds an integration test exercising the entire lifecycle of a Participant (including termination - which was previously lacking), communicating with …
> XP-436 Reinstate FINISHED heartbeat from Coordinator

- docs/network_architecture.rst
- setup.py
- tests/__init__.py
- tests/test_coordinator.py
- tests/test_grpc.py
- xain_fl/__init__.py
- xain_fl/coordinator/coordinator.py
- xain_fl/helloproto/numproto_client.py
- xain_fl/helloproto/numproto_server.py
[XP-333-Protocol Buffer - Couldn't build proto file at starting of participant](https://xainag.atlassian.net/browse/XP-333)
* Replaced `numproto` with `xain-proto`
No
---
> XP-333 Replace numproto with xain-proto

- docs/conf.py
- setup.py
- xain_fl/coordinator/coordinator.py
https://xainag.atlassian.net/browse/XP-505
This fixes two issues:
- make the docstrings more readable by having symbols types automatically inferred by sphinx
- have working links to symbols types in the generated documentation
I will split this task in multiple pull request to minimize the risk of conflicts, since this affects the entire codebase.
Optional: Next Step
Clean up other modules
---
> XP-505: docstrings cleanup

- xain_fl/cli.py
- [XP-510](https://xainag.atlassian.net/browse/XP-510)
- allow for zero epochs when running the coordinator from the cli
- none
---
> XP-510 allow zero epochs

- scripts/create_git_hooks.sh
- scripts/format.sh
- scripts/rm_caches.sh
- scripts/test.sh
https://xainag.atlassian.net/browse/XP-498
On some platforms, /bin/bash does not exist. Using /usr/bin/env let
users choose which `bash` should be used to run the scripts.
See also:
- https://en.wikipedia.org/wiki/Shebang_(Unix)#Portability
- https://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my
---
> XP-498: more generic shebangs

- setup.py
[XP-277](https://xainag.atlassian.net/browse/XP-227)
Fixes the reference to `xain-sdk==0.3.0` on setup.py for releasing to PyPI
No
---
> XP-277 Fix reference to xain-sdk on setup.py

- tests/store.py
- tests/test_coordinator.py
- tests/test_grpc.py
- xain_fl/coordinator/coordinator.py
[XP-404](https://xainag.atlassian.net/browse/XP-404) (specifically [XP-479](https://xainag.atlassian.net/browse/XP-479))
This lays the groundwork for supporting weights initialisation in the Participant. Currently, the Coordinator is responsible for providing the initial weights to its participants for training, but it would be more desirable for this to be generated by the participants themselves.
For this, we adopt a new convention of enumerating rounds from **0** where the 0th round is usually intended to be for initialisation purposes but (for sake of simplicity and uniformity) is conceptually no different from any other round i.e. it still follows the same `StartTrainingRound`-`EndTrainingRound` communication:
- In `StartTrainingRound`, empty weights are distributed to participants. …
> XP-479 Start training rounds from 0

- Dockerfile.dev
https://xainag.atlassian.net/browse/DO-58
Some dependencies require a very long compilation: protobuf, numpy,
grpcio. To avoid having to re-install these packages every time, we
pre-install them so that they are cached.
However, we cannot just pre-install a few packages, because we don't
know exactly which version `pip` will pick for them. Instead, we
give `pip` all the package's dependencies, and let it resolve and
install them.
---
> DO-58: cache xain-fl dependencies in Docker

- README.md
- docs/network_architecture.rst
- [XP-407](https://xainag.atlassian.net/browse/XP-407)
- remove numpy weights file requirement from documentation
- none
---
> XP-407 update documentation

- .github/workflows/development_pull_request.yml
- .github/workflows/master_pull_request.yml
- .github/workflows/master_tag.yml
[DO-48](https://xainag.atlassian.net/browse/DO-48)
This PR creates an `sdist` and `wheel` release of the project, based on a git tag pushed for `master` branch, and uploads it as an artifact to download.
No
Create testing packages off of branches named following SemVer nomenclature
---
> DO-48 :snowflake: :rocket: Build stable package on git tag with SemVer

- docker/entrypoint.sh
https://xainag.atlassian.net/browse/XP-456
Fix the `coordinator` command in the docker "release" image.
---
> XP-456: fix coordinator command

- xain_fl/__main__.py
- xain_fl/logger.py
https://xainag.atlassian.net/browse/PB-380
`get_logger()` does not just create a logger and wrap it into
structlog. It actually also creates an "aimetrics" logger and
reconfigures structlog. This commit split `get_logger()` so that it
only creates a logger.
---
> PB-380: split get_logger()

- tests/conftest.py
- tests/store.py
- tests/test_grpc.py
- xain_fl/__main__.py
- xain_fl/coordinator/coordinator_grpc.py
- xain_fl/coordinator/store.py
- xain_fl/serve.py
- introduce an abstract class that defines the storage API
- document the `xain_fl.coordinator.store` module
- rename `tests.store.TestStore` into `tests.store.FakeS3Store`
https://xainag.atlassian.net/browse/PB-382
---
> PB-382: cleanup storage

- configs/example-config.toml
- configs/xain-fl.toml
- tests/test_config.py
- xain_fl/__main__.py
- xain_fl/config/__init__.py
- xain_fl/config/schema.py
- xain_fl/logger.py
**This is based on https://github.com/xainag/xain-fl/pull/242**
-----
https://xainag.atlassian.net/browse/PB-381
Add a new `[logging]` section to the configuration file. For now, this
section only provides a `level` key which can be one of the log levels
supported by default by the Python standard library: notset, debug,
info, warning, error, critical.
In the future, this `[logging]` section could be used to provide more
knobs for logging customatization: enabling colors for the terminal
handler, specifying a path for logging into a file, etc.
References:
xainag.atlassian.net/browse/PB-381
--- …
> PB-381: make the log level configurable

- docker-compose-dev.yml
- docker-compose.yml
[PB-353](https://xainag.atlassian.net/browse/PB-353) -> [DO-59](https://xainag.atlassian.net/browse/DO-59)
Updates `docker-compose-dev.yml` and `docker-compose.yml` for provisioning Redis 5.x.
Redis will be used as in-memory key-value storage for the Coordinator to persist its state externally.
No
---
> DO-59 Provision Redis 5.x for persisting states for the Coordinator

- docker-compose-dev.yml
- docker-compose.yml
[PB-172](https://xainag.atlassian.net/browse/PB-172) -> [DO-57](https://xainag.atlassian.net/browse/DO-57)
Updates `docker-compose-dev.yml` and `docker-compose.yml` for provisioning InfluxDB.
InfluxDB will be used as Time-Series Database for the Coordinator to store historical data over metrics from itself and registered participants.
No
---
> DO-57 Provision InfluxDB for storing coordinator/participant metrics

- tests/test_grpc.py
- xain_fl/coordinator/heartbeat.py
https://xainag.atlassian.net/browse/PB-104
This adds a test reproducing the following exception, and provides a
fix for it:
```
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.6/threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "/app/xain_fl/coordinator/heartbeat.py", line 45, in monitor_heartbeats
time.sleep(next_expiration)
ValueError: sleep length must be non-negative
```
Detailed explanation:
There is a timing issue in the `monitor_hearbeats()` function, that is
more likely to occur when we have many participants. Here is a
simplified and commented version of the code that explains the issue in
more details:
```python
class …
```
> PB-104: Fix exception in monitor_hearbeats()

- tests/conftest.py
- tests/store.py
- tests/test_grpc.py
- xain_fl/__main__.py
- xain_fl/coordinator/coordinator.py
- xain_fl/coordinator/coordinator_grpc.py
- xain_fl/coordinator/store.py
- xain_fl/serve.py
This is based on #245, which should be merged first.
https://xainag.atlassian.net/browse/PB-383
We now store the weights at the end of *each* round instead of the end
of the final round.
---
> PB-383 write aggregated weights after each round

- xain_fl/__main__.py
https://xainag.atlassian.net/browse/PB-122
Guard the call to `main()` at the end of `__main__.py`. Otherwise
we're starting the coordinator twice by calling the `coordinator`
command: once when `__main__.py` is imported, and once when the
entrypoint (`__main.py__::main`) is called.
---
> PB-122: handle sigint properly

- tests/test_grpc.py
In https://github.com/xainag/xain-fl/pull/248, we replaced the call to
`time.sleep()` in `monitor_hearbeats()` by a call to
`threading.Event.wait()` to optimize for cases where the termination
event is set while we're sleeping. But, that made tests with mocks of
`time.sleep()` slower. This commit fixes that by mocking
`threading.Event.wait()` instead of `time.sleep()` in these tests.
https://github.com/xainag/xain-fl/pull/248
https://xainag.atlassian.net/browse/PB-104
---
> PB-104: make the tests fast again

- configs/example-config.toml
- configs/xain-fl.toml
- docker-compose-dev.yml
- setup.py
- tests/test_config.py
- tests/test_metric_store.py
- xain_fl/__main__.py
- xain_fl/config/__init__.py
- xain_fl/config/schema.py
- xain_fl/coordinator/coordinator.py
- xain_fl/coordinator/metrics_store.py
- xain_fl/coordinator/round.py
[PB-351 Implement metric proxying/re-routing on coordinator for metrics shipped by participant](https://xainag.atlassian.net/browse/PB-351)
* store participant metrics on InfluxDB
* InfluxDBClient is configurable via the config.toml
* feature is enabled in `docker-compose-dev` only
* Adjust the metrics messages to meet the needs of InfluxDB.(PB-390)
---
> PB-351 Store participant metrics

- setup.py
It seems that pip resolves the dependencies by profile. If the [doc]
profile is installed first, docutils ~= 0.16 is picked up, and when
xain-fl's install_requires is resolved, pip sees that docutils is
already installed but has an incompatible version.
I suspect the order in which pip handles the profiles depends on your
environment (pip version, platform, python version, etc.) which is why
we don't see this issue consistently.
As a workaround we explicitely depends on docutils in the [doc]
profile and restrict the version here.
https://xainag.atlassian.net/browse/PB-116
---
**Merge request …
> PB-116: pin docutils version

- .github/workflows/development_pull_request.yml
- .github/workflows/master_pull_request.yml
- xain_fl/coordinator/metrics_store.py
[DO-73](https://xainag.atlassian.net/browse/DO-73)
Disable continue_on_error for all jobs in CI
No
---
> DO-73 :green_heart: Disable continue_on_failure for CI jobs

- .github/workflows/development_pull_request.yml
- .github/workflows/master_pull_request.yml
- scripts/test.sh
- [PB-119](https://xainag.atlassian.net/browse/PB-119)
- enable `--diff` for `isort` calls
- none
---
> PB-119 enable isort diff

- configs/example-config.toml
- configs/xain-fl.toml
- tests/store.py
- tests/test_config.py
- tests/test_coordinator.py
- tests/test_grpc.py
- tests/test_metric_store.py
- xain_fl/__main__.py
- xain_fl/config/schema.py
- xain_fl/coordinator/coordinator.py
- xain_fl/coordinator/metrics_store.py
- xain_fl/coordinator/store.py
- xain_fl/serve.py
Add code for reading participants weights from S3.
Implementation details:
We split the AbstractStore class in to separate abstract classes:
- `AbstractAggregatedWeightsStore` is used to upload the aggregated
weights to S3
- `AbstractParticipantsWeightsStore` is used to download participants
weights from S3
The separation also allows us to use a dummy `NullObjectStore` class
for retrieving the participants weights, while using the real
`AggregatedWeightsS3Store` class for uploading aggregated weights.
In the future, it may be useful to provide different configurations
for the storage service used for aggregated weights and the storage
service used for participants weights: they may use different
credentials, permissions, endpoints, etc.
https://xainag.atlassian.net/browse/PB-269
--- …
> PB-269: enable reading participants weights from S3

- .github/workflows/development_e2e_tests.yml
- .github/workflows/development_pull_request.yml
- .github/workflows/master_pull_request.yml
- .github/workflows/master_tag.yml
- .github/workflows/release_branch.yml
[DO-72](https://xainag.atlassian.net/browse/DO-72) [DO-47](https://xainag.atlassian.net/browse/DO-47)
CI builds test packages for release branches. Jobs are renamed to be consistent across all repos. 
GitHub Actions only parses the jobs present in the default branch, in our case, `master`, thus the need to merge to `master`
No
---
> Hotfix: update ci

- setup.py
- tests/test_grpc.py
Follow up task to complete [PB-352](https://xainag.atlassian.net/browse/PB-352)
* Added participant config
No
---
> PB-352 Add sdk config

- tests/test_grpc.py
Follow up ticket of:
[PB-385 Replace time.sleep() with Event.wait() in SDK message_loop function](https://xainag.atlassian.net/browse/PB-385)
* fixed sdk test
No
---
> PB-385 Fix xain-sdk test

- docker-compose-dev.yml
[DO-66](https://xainag.atlassian.net/browse/DO-66)
This MR Adds Keycloack to the development docker-compose for OpenID Connect usage alongside Grafana
No
[DO-78](https://xainag.atlassian.net/browse/DO-78) Will follow up adding Grafana.
A third PR may be required to finish the set-up of OpenID Connect for Grafana
---
> DO-66 :sparkles: Add keycloak

- configs/example-config.toml
- configs/xain-fl.toml
- tests/test_config.py
- xain_fl/__main__.py
- xain_fl/config/schema.py
- xain_fl/coordinator/coordinator.py
- xain_fl/coordinator/heartbeat.py
- xain_fl/coordinator/metrics_store.py
- xain_fl/fl/coordinator/aggregate.py
- xain_fl/logger.py
- xain_fl/serve.py
[PB-401](https://xainag.atlassian.net/browse/PB-401)
* enable console renderer in xain fl
No
---
> PB-401 Add console renderer

- xain_fl/coordinator/coordinator.py
[PB-402](https://xainag.atlassian.net/browse/PB-402)
* made the current logs more expressive and less visual noisy:
- `reply=LATER` instead of `reply=1`
- `state=ROUND` instead of `state=1`
- `message_type=HeartbeatRequest` instead of `message_type=<class 'xain_proto.fl.coordinator_pb2.HeartbeatRequest'>`
* add logs for message_byte_size, current_participants_count
No
---
> PB-402 Add more logs

- tests/test_coordinator.py
- xain_fl/coordinator/coordinator.py
- xain_fl/coordinator/round.py
- xain_fl/fl/coordinator/controller.py
[PB-398](https://xainag.atlassian.net/browse/PB-391)
Adds proper support for round resumption in the Coordinator.
This merge request adds some resilience to the Coordinator in the face of Participant dropouts. In particular, when there is a dropout mid-round, the Coordinator pauses the round by going to standby. When enough Participants connect again, the round is resumed. While the idea of round resumption has been in the Coordinator for some time (and has recently been supported properly [in the Participant too](https://github.com/xainag/xain-sdk/pull/47)), up until now it has not been properly exercised, and this MR fixes the obvious faults, so that:
- `remove_participant` previously ignored the collection of selected Participants for a round; now it also takes that into account.
- …
> PB-398 Round resumption in Coordinator

- setup.py
- xain_fl/coordinator/coordinator.py
- [PB-425](https://xainag.atlassian.net/browse/PB-425) (automatically solves [PB-409](https://xainag.atlassian.net/browse/PB-409))
- only write metrics when the respective message is not empty (e.g. no metrics for weight init round)
- keep track of the number of epochs for the current training round
- none
---
> PB-425 split weight init from training

- docker-compose-dev.yml
- tests/conftest.py
- tests/test_grpc.py
- tests/test_metric_store.py
- xain_fl/coordinator/coordinator.py
- xain_fl/coordinator/metrics_store.py
[PB-428 Send coordinator states to InfluxDB ](https://xainag.atlassian.net/browse/PB-428)
* `number_of_selected_participants`, `round` and `state` are send to influxDB
---
> PB-428 send coordinator states

- tests/conftest.py
- xain_fl/coordinator/metrics_store.py
[PB-434 Separate participant metrics from coordinator metrics](https://xainag.atlassian.net/browse/PB-434)
* adjust jsonschema (ensure that the value of measurement is always `participant`)
* fix tests
No
---
> PB-434 separate metrics

- tests/conftest.py
- tests/test_grpc.py
- tests/test_metric_store.py
- xain_fl/coordinator/coordinator.py
- xain_fl/coordinator/metrics_store.py
[PB-431](https://xainag.atlassian.net/browse/PB-431)
* added a `write_participant_metrics` method (the method can be used to write participant metrics that are collected on the coordinator site (round, state) into influxdb 
* updated/added tests
No
---
> PB-431 send participant state to influxdb

- configs/example-config.toml
- configs/xain-fl.toml
- docker-compose-dev.yml
- setup.py
- tests/conftest.py
- tests/store.py
- tests/test_config.py
- tests/test_coordinator.py
- tests/test_grpc.py
- xain_fl/__main__.py
- xain_fl/config/schema.py
- xain_fl/coordinator/coordinator.py
- xain_fl/coordinator/store.py
https://xainag.atlassian.net/browse/PB-159
Needs to be merged along with:
- https://github.com/xainag/xain-proto/pull/25
- https://github.com/xainag/xain-sdk/pull/88
- https://github.com/xainag/xain-fl/pull/298
Remove the weights from the gRPC messages. From now on, weights will
be exchanged via s3 buckets.
The sequence diagram below illustrate this new behavior.
At the beginning of a round (1) the selected participants send a
`StartTrainingRound` request, and the coordinator response with the
same `StartTrainingRoundResponse` that does not contain the global
weights anymore.
Instead, the participant fetches these weights from the store (2). S3
buckets are key-value stores, and the key for global weights is the
round number.
Then, the participant trains. Once done, it uploads its local …
> PB-159: remove weights from gRPC messages

- setup.py
- tests/test_grpc.py
https://xainag.atlassian.net/browse/PB-159
Follow-up of https://github.com/xainag/xain-fl/pull/298
---
> PB-159: update xain-{proto,sdk} dependencies to the right branch

- configs/example-config.toml
- tests/test_config.py
- xain_fl/config/schema.py
- xain_fl/serve.py
[PB-439](https://xainag.atlassian.net/browse/PB-439)
* made thread pool workers configurable
No
---
> PB-439 Make thread pool workers configurable

- configs/example-config.toml
- tests/test_config.py
- tests/test_grpc.py
- xain_fl/__main__.py
- xain_fl/config/schema.py
- xain_fl/coordinator/__init__.py
- xain_fl/coordinator/coordinator.py
- xain_fl/coordinator/participants.py
[PB-44 Make HEARTBEAT_TIME and HEARTBEAT_TIMEOUT configurable](https://xainag.atlassian.net/browse/PB-44)
*  Made `HEARTBEAT_TIME` and `HEARTBEAT_TIMEOUT` configurable
No
---
> PB-44 add heartbeat time and timeout to config

- tests/test_grpc.py
- xain_fl/coordinator/coordinator.py
- [PB-407](https://xainag.atlassian.net/browse/PB-407)
- small adjustments for increased debug-level logging in the participant state machine
- ~[xain-sdk mr](https://github.com/xainag/xain-sdk/pull/94) must be merged first~
---
> PB-407 add more debug level logging

- docs/network_architecture.rst
https://xainag.atlassian.net/browse/PB-314
Document the new weights distribution mechanism via S3 buckets
---
> PB-314: document the new weight exchange mechanism

- .rustfmt.toml
- This file has been forgotten when we moved the rust code from the root of the repo to the `rust/` directory
- The only option set in this file is now a default of `rustfmt`
> remove the rustfmt config file

- rust/Cargo.toml
This fixes the following warning:
```
warning: only one of `license` or `license-file` is necessary
```
> remove redundant key in Cargo.toml

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/bin/coordinator.rs
- rust/src/common/metric_store/influxdb.rs
- rust/src/coordinator/core/service.rs
> Upgrade InfluxDB to 0.1.0

- rust/src/pet/coordinator.rs
- rust/src/pet/participant.rs
- rust/src/pet/utils.rs
**References**
- [PB-484](https://xainag.atlassian.net/browse/PB-484) including [PB-498](https://xainag.atlassian.net/browse/PB-498), [PB-499](https://xainag.atlassian.net/browse/PB-499), [PB-500](https://xainag.atlassian.net/browse/PB-500)
**Summary**
- compose and validate "sum", "update" and "sum2" messages of the PET protocol
- provide multi-layer buffers to serialize and deserialize the messages
**Open tasks**
- none
> PB-484 pet messages

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/aggregator/mod.rs
- rust/src/aggregator/py_aggregator.rs
- rust/src/aggregator/rpc.rs
- rust/src/coordinator/core/mod.rs
- rust/src/coordinator/core/service.rs
- rust/src/lib.rs
- rust/src/tests/coordinator.rs
- rust/src/tests/lib/coordinator.rs
- rust/src/tests/lib/mod.rs
- rust/src/tests/lib/rpc/aggregator.rs
- rust/src/tests/lib/rpc/mod.rs
- rust/src/tests/mod.rs
The main tasks, _ie_ that tasks that implement most of the business
logic are `aggregator::Service` for the aggregator and
`coordinator::Service` for the coordinator. This commit implements a
first tests for `coordinator::core::Service`.
In order to test the service, we need to control its inputs and
outputs
There are three source:
- an RPC server that receives requests from the network and sends back responses
- an RPC client that sends requests to the network and receives responses back
- an REST API that receives requests from the network, and sends back responses
However, two of these are not _direct_ sources of the `Service`. The
API and RPC server layers are already isolated and run in their own
task. They communicate with the `Service` via a `Handle` as
illustrated below:
``` …
```
> PB-570: add the first coordinator::core::Service test

- rust/src/coordinator/rpc.rs
- rust/src/tests/aggregator.rs
- rust/src/tests/lib/aggregator.rs
- rust/src/tests/lib/mod.rs
- rust/src/tests/lib/rpc/coordinator.rs
- rust/src/tests/lib/rpc/mod.rs
- rust/src/tests/mod.rs
**Summary**
- add first aggregator io test
> PB-569 first aggregator test

- rust/src/pet/coordinator.rs
- rust/src/pet/mod.rs
- rust/src/pet/participant.rs
- rust/src/pet/utils.rs
**References**
- [PB-537](https://xainag.atlassian.net/browse/PB-537) including [PB-551](https://xainag.atlassian.net/browse/PB-551), [PB-552](https://xainag.atlassian.net/browse/PB-552), [PB-553](https://xainag.atlassian.net/browse/PB-553), [PB-554](https://xainag.atlassian.net/browse/PB-554), [PB-555](https://xainag.atlassian.net/browse/PB-555), [PB-556](https://xainag.atlassian.net/browse/PB-556), [PB-557](https://xainag.atlassian.net/browse/PB-557)
**Summary**
- add unit tests for message composition
- add unit tests for message validation
- add unit tests for utils
- add message wrappers
**Open Tasks**
- follow up task: unify the message buffer structure ([PB-588](https://xainag.atlassian.net/browse/PB-588))
> PB-537 pet tests

- rust/src/aggregator/api.rs
- rust/src/aggregator/py_aggregator.rs
- rust/src/aggregator/rpc.rs
- rust/src/aggregator/service.rs
- rust/src/bin/coordinator.rs
- rust/src/coordinator/core/service.rs
- rust/src/tests/aggregator.rs
- rust/src/tests/coordinator.rs
- rust/src/tests/lib/aggregator.rs
- rust/src/tests/lib/rpc/aggregator.rs
This is the first part of https://xainag.atlassian.net/browse/PB-598.
Second part will be mapping the errors introduced by the PR to HTTP error codes in `warp`.
Summary and motivation
======================
In order to return proper errors to the clients in the API layer, we
need errors to be reported accurately within the service: a mere
`Result<T, ()>` is not good enough. This commit refactors the error
handling in the aggregator service, such that any error (whether it
happens in `PyAggregator`, in the RPC layer, or in the protocol
itself) is propagated back to the `ServiceHandle`, which is the
entrypoint for making requests to the service.
Implementation
==============
`ServiceError<T>`
-----------------
The `ServiceHandle` methods now return a `ServiceError<T>`, where `T`
depends on …
> PB-598: refactor error handling in the aggregator

- .github/workflows/rust.yml
- CONTRIBUTING.md
This fixes the spurious issue we've been seeing in CI, by running the python tests in a single thread.
> fix python tests in CI

- scripts/bump_version.sh
This is an interactive script that automates some of the checks, and is able create a tag locally. The user still has to push manually.
It's not particularly beautiful because I'm not well versed in bash or in git porcelain commands, but `shellcheck` doesn't emit any warning, so it's not _that_ bad.
> add a to facilitate releasing a new version

- rust/rustfmt.toml
- rust/src/aggregator/rpc.rs
- rust/src/coordinator/api.rs
**Summary**
- reintroduce the `rustfmt.toml` config file, because `merge_imports` is not yet stable and therefore `false` by default (https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#merge_imports)
> add rustfmt.toml

- rust/src/coordinator.rs
- rust/src/lib.rs
- rust/src/message/mod.rs
- rust/src/message/sum.rs
- rust/src/message/sum2.rs
- rust/src/message/update.rs
- rust/src/participant.rs
Instead of having two blocks:
```rust
impl Foo<&A, &B, &C> {}
impl Foo<A, B, C> {}
```
we can use the `Borrow` trait, which has this precise purpose. To
quote the [book](https://doc.rust-lang.org/1.27.2/book/first-edition/borrow-and-asref.html#which-should-i-use):
> Choose Borrow when you want to abstract over different kinds of
> borrowing, or when you’re building a data structure that treats
> owned and borrowed values in equivalent ways
For convenience, this commit also introduces a `Certificate`
placeholder, just so that we don't have `Vec<u8>` hanging around.
Finally, this commit renames various `Foo:from` methods into
`Foo::new`. By convention, `from()` is kind of reserved for From
implementations. Perhaps we could have `from_parts()` and
`into_parts()` instead.
> use Borrow to implement messages

- docker/Dockerfile.release
- docker/docker-compose-release.yml
This PR fixes `docker-compose-release.yaml` and removes the `telemetry` flag from the release builds
> DO-105 :pencil: Remove telemetry flag from release image. Update compose

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/bin/main.rs
- rust/src/coordinator.rs
- rust/src/lib.rs
- rust/src/mask/mod.rs
- rust/src/participant.rs
- rust/src/service.rs
- rust/src/service/data.rs
- rust/src/service/handle.rs
- rust/src/service/mod.rs
This commit introduce a service module. The main type is
`service::Service`. It is a Future that handles events (incoming
messages, protocol state changes, etc.), and drives the protocol.
Changes to the protocol state machine
-------------------------------------
To update the state machine, the service calls
`Coordinator::handle_message()` when new messages arrive. The
`Coordinator` updates its state accordingly and emits `ProtocolEvent`
events for the service to handle. Currently, the coordinator emits an
event every time it starts a new phase.
Service state
-------------
The service needs to keep track of some data. This is what
`service::Data` is for. Some data is common to all the protocol
phases, but some is specific to the current protocol phase. The pase
specific data is …
> Service implementation

- docker/Dockerfile
The dockerfile wasn't building because the wrong parameters were being passed on to `cargo`. This PR fixes this issue.
> PB-704 :ambulance: :whale: Fix dockerfile not building

- rust/src/lib.rs
- rust/src/mask/mod.rs
**References**
- [PB-735](https://xainag.atlassian.net/browse/PB-735)
**Summary**
- fix a bug during unmasking by checking that the given `no_models` actually conforms to the chosen mask configuration. this checks that the `ModelType` of the mask config holds. the `GroupType`, `DataType` and `BoundType` hold because they're enforced via modulus addition.
- casting `numbers_from(ratios)` might fail if a ratio is not representable as the number's data type. this accounts for that the choice of the mask configuration should fit the models and the scalars, but it's not guaranteed to.
If unmasking fails with the new checks in place, then this should only ever happen if the aggregated model isn't representable in the primitive data type in the first place. This can happen due to the choice of …
> PB-735 ensure mask configuration before unmasking

- .github/workflows/rust.yml
- docker/docker-compose.yml
**References**
* [PB-718](https://xainag.atlassian.net/browse/PB-718)
* [PB-717](https://xainag.atlassian.net/browse/PB-717)
**Summary**
1. Updated docker-compose file:
- Removed all existing services
- Added minio service (I took the same setup we had in the old python repo)
2. Updated Rust CI:
- Added a smoke test job which starts all external dependencies (in the moment it is only minio) via docker-compose.
- The smoke test job runs tests that are marked with the `[#ignore]` annotation only.
- The `[#ignore]` annotation is used to distinguish between simple unit tests and tests that depend on an external service.
- It is the best solution I have been able to find so far. We can also remove the `[#ignore]`  annotation and run them together in one job but I think it will make development …
> PB-718 Update CI

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/mask/mod.rs
- rust/src/mask/model.rs
- rust/src/service/data.rs
- rust/src/service/handle.rs
Adds the global model to the round parameters response. 
The response of `get_round_parameters()` will depend on the current round and protocol phase. The possible responses are.
First Round `Idle` phase:
```
round_parameter_data = None
```
First Round `Sum` phase:
```
round_parameter_data = {
round_parameter: Some(round parameters of the first round)
global_model: None
}
```
First/Second Round `EndRound/Idle` phase:
```
round_parameter_data = {
round_parameter: None
global_model: Some(global model of the first round)
}
```
Second Round `Sum` phase:
```
round_parameter_data = {
round_parameter: Some(round parameters of the second round)
global_model: Some(global model of the first round)
}
```
Second/Third Round `EndRound/Idle` phase:
```
round_parameter_data = {
round_parameter: None …
```
> Add global model in round parameter

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/bin/test-drive.rs
- rust/src/client.rs
- rust/src/coordinator.rs
- rust/src/lib.rs
- rust/src/message/message.rs
- rust/src/participant.rs
- rust/src/service/mod.rs
Introduces `Client` which can be thought of as a wrapper around `Participant`. It deals with the communication with the `Service`. Currently this is designed to only work _locally_ with a running `Service`, hence it works directly with a service `Handle`. Later this will be changed when it becomes fully network-capable. Also, this version does not yet support actual training of models.
This also adds a simple test driver to show clients running alongside a service.
References:
[PB-664](https://xainag.atlassian.net/browse/PB-664) (Participant with PET logic)
[PB-732](https://xainag.atlassian.net/browse/PB-732) (Integration test)
> PB-664 Client

- rust/src/client.rs
**update**. This addresses a break in the build introduced in https://github.com/xainag/xain-fl/pull/397
- now compatible with the changes around round parameters introduced in https://github.com/xainag/xain-fl/pull/411
- [PB-783](https://xainag.atlassian.net/browse/PB-783)
--------------------
This compiles, but isn't quite as it should be. In the loop of `during_round`, we poll for `round_params_data`. Now the "old" `round_params` are inside, and also `Option`al. So really we should be polling until `round_params` is _also_ available. What we'd really like is something like
```rust
// doesn't compile!
let round_params = loop {
if let Some(round_params_data) = self.handle.get_round_parameters().await {
if let Some(round_params) = round_params_data.round_parameters {
break round_params;
} …
```
> WIP fix to poll round params data

- rust/src/client.rs
- rust/src/coordinator.rs
- rust/src/lib.rs
- rust/src/mask/model.rs
- rust/src/participant.rs
- rust/src/sdk/api.rs
- rust/src/sdk/mod.rs
- rust/src/service/data.rs
- rust/src/service/handle.rs
- rust/src/service/mod.rs
**References**
- [PB-670](https://xainag.atlassian.net/browse/PB-670)
**Summary**
- ~the `Client` introduced here is just a mock for now, it should be replaced by the networking client or a wrapper around that when that is merged;~ also some of the logic needs to be implemented then marked as `TODO`s
- generics as well as methods can't be exposed to C, therefore most of this code exposes functions for each primitive data type
- implement getters for the global model: the global model is converted to a model of primitive type and cached, a "mutable slice" is returned to the caller
- implement setters for the local model: take a "mutable slice" and convert it's data to a model, ~provides a new iterator for that if the slice doesn't point to the cached model~
- implement a callback: this is …
> PB-670 C API for FL

- rust/src/client.rs
- rust/src/participant.rs
- rust/src/sdk/api.rs
- rust/src/service/handle.rs
**References**
- [PB-774](https://xainag.atlassian.net/browse/PB-774)
**Summary**
- wrap the `Client` and a tokio `Runtime` into a `FFIClient`
- create a custom runtime in `new_client()` and start the client in that runtime in `run_client()`
- remove the callback experiment and replace it with a purposeful callback in `run_client()`
- implement error handling across the FFI boundary
- update docs and tests
- add `new_model()` for a zero-initialized cached primitive model and restrict `update_model()` to take no foreign memory but only cached models
- simplify the type-suffixed functions by removing the suffix and replace it with type flags and void pointers instead
> PB-774 client async runtime

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/bin/main.rs
- rust/src/bin/test-drive-net.rs
- rust/src/bin/test-drive.rs
- rust/src/client.rs
- rust/src/coordinator.rs
- rust/src/lib.rs
- rust/src/request.rs
- rust/src/rest.rs
- rust/src/sdk/api.rs
- rust/src/service/data.rs
- rust/src/service/handle.rs
- rust/src/service/mod.rs
**_update_**. Addresses divergences from a rebase, mostly from the new C API changes.
- separated `get_sum_dict_and_scalar` into two separate endpoints (changes on client and server side).
- updates to the C API to work directly with the global model, rather than in serialised form.
- resolved divergences to `Client` and tidied it a bit
- slight updates to `test-drive`s to make them work post-rebase - at the moment still using just `Client`, w/o the C API for now.
Most of the above in [this commit](https://github.com/xainag/xain-fl/pull/420/commits/81324b160e44a6f68bb34916ca23a588defc43f6).
=====
This merge request enables clients and the service to communicate with each other over HTTP.
On the client-side is a new `Proxy` type in `request.rs`, which a `Client` will use to communicate …
> networking over HTTP

- rust/src/client.rs
- rust/src/coordinator.rs
- rust/src/mask/masking.rs
- rust/src/participant.rs
- rust/src/request.rs
- rust/src/rest.rs
- rust/src/service/data.rs
- rust/src/service/handle.rs
- rust/src/service/mod.rs
**References**
- [PB-794](https://xainag.atlassian.net/browse/PB-794)
**Summary**
- add a model/mask length GET request to the rest api
- handle the request by the in-memory handle and the network handle
- adjust the coordinator, participant and client to use the model/mask length information in the sum2 phase
> PB-794 fix mask length

- .github/workflows/rust.yml
- CONTRIBUTING.md
- docker/Dockerfile
- docker/Dockerfile.release
- docker/install_rust.sh
- rust/rust-toolchain
- rust/rustfmt.toml
- rust/src/lib.rs
- rust/src/message/buffer.rs
**References**
- [PB-840](https://xainag.atlassian.net/browse/PB-840)
**Summary**
- rewrite the two occurrences of unstable feature usage
- set the rust toolchain, github ci and dockerfiles to rust stable
As soon as this is merged, please make sure that you are using stable rust as well, otherwise it might cause conflicts when pushing merge requests to the CI. Therefore please check that:
- the `RUSTUP_TOOLCHAIN` env variable is either not set or set to stable
- `rustup override list` doesn't show any nightly overrides for the `xain_fl` directory (can for example be wiped via `rustup override unset` and `rustup override unset --nonexistent`)
- either the default toolchain is set to stable or the toolchain for the `xain_fl` directory is set to stable (can for example be set via `rustup …
> PB-840 switch to stable rust

- rust/src/sdk/api.rs
- rust/src/sdk/mod.rs
**References**
- [PB-846](https://xainag.atlassian.net/browse/PB-846)
**Summary**
- add temporary, undocumented wrappers to the boolean functions of the API for Dart
- update the [confluence page](https://xainag.atlassian.net/wiki/spaces/FP/pages/670269471/Dart+FFI) accordingly
> PB-846 add bool wrappers for dart

- k8s/coordinator/base/deployment.yaml
- k8s/coordinator/development/kustomization.yaml
I'm opening this as a "Draft PR" as I still want to wait for https://github.com/xainag/xain-fl/pull/430 to be merged first, due to changes on the Dockerfile.
I will then rebase this one and mark it as ready for review.
---
For the time being, so I could move forward and update the `coordinator` in our development Kubernetes Cluster, I did local changes to the Dockerfile on my own branch, just so I could build and push the updated `xain/xain-fl:development` to Docker Hub.
> PB-797 Replace/update coordinator in Kubernetes

- rust/src/crypto/encrypt.rs
- rust/src/crypto/hash.rs
- rust/src/crypto/mod.rs
- rust/src/crypto/prng.rs
- rust/src/crypto/sign.rs
- rust/src/lib.rs
- rust/src/mask/masking.rs
- rust/src/mask/seed.rs
- rust/src/message/message.rs
- rust/src/participant.rs
- rust/src/services/messages/message_parser.rs
- rust/src/state_machine/coordinator.rs
- rust/src/state_machine/events.rs
- rust/src/state_machine/mod.rs
- rust/src/state_machine/phases/idle.rs
**References**
- [PB-875](https://xainag.atlassian.net/browse/PB-875)
**Summary**
- add module level documentation
- update struct and method documentation
- unravel import indirections
- consistify naming and usage of the newly introduced `KeyPair`
note that this requires `cargo +nightly doc` to generate proper internal links, which is not an issue since this is supported by the hosted rust docs as well.
> PB-875 document crypto module

- rust/src/crypto/sign.rs
- rust/src/mask/config/mod.rs
- rust/src/mask/config/serialization.rs
- rust/src/mask/masking.rs
- rust/src/mask/mod.rs
- rust/src/mask/model.rs
- rust/src/mask/object/mod.rs
- rust/src/mask/object/serialization.rs
- rust/src/mask/seed.rs
**References**
- [PB-870](https://xainag.atlassian.net/browse/PB-870)
**Summary**
- add module level documentation
- update struct and method documentation
note that this requires `cargo +nightly doc` to generate proper internal links, which is not an issue since this is supported by the hosted rust docs as well.
> PB-870 document mask module

- rust/src/state_machine/events.rs
- rust/src/state_machine/mod.rs
- rust/src/state_machine/phases/mod.rs
> Fix typos in state machine docs

- rust/src/rest.rs
Documents the server-side of the networking code.
This was left out of #437 since it is not part of the `client` module.
> document HTTP server

- configs/config.toml
- configs/docker-dev.toml
- rust/src/state_machine/phases/error.rs
- rust/src/state_machine/phases/shutdown.rs
**Summary**
- added the broadcasting of PhaseEvent in error and shutdown state 
- set the filter of  `http` to `warn` because each http request creates an info log entry
> Add missing PhaseEvent in error and shutdown state

- scripts/bump_version.sh
- Commit the `Cargo.lock` changes before running `cargo publish`
- Clarify interaction when the script that no change has been made to the CHANGELOG
> Fix update script

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/mask/config/mod.rs
- rust/src/mask/object/serialization.rs
**References**
- [PB-927](https://xainag.atlassian.net/browse/PB-927)
**Summary**
- update the `num` dependency to `0.3.0`
- fix a breaking change in byte counting for the mask serialization
- add some target checks for the mask serialization
> PB-927 update num dependency and add target checks

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/crypto/encrypt.rs
- rust/src/crypto/hash.rs
- rust/src/crypto/mod.rs
- rust/src/crypto/sign.rs
- rust/src/mask/masking.rs
- rust/src/mask/seed.rs
- rust/src/message/buffer.rs
- rust/src/message/payload/sum.rs
- rust/src/message/payload/sum2.rs
- rust/src/message/payload/update.rs
- rust/src/services/mod.rs
- rust/src/services/tests/fetchers/mod.rs
- rust/src/services/tests/mod.rs
- rust/src/services/tests/utils.rs
- rust/src/state_machine/coordinator.rs
- add two new dev dependencies: `tokio-test` and `tower-test`.
- add a `LENGTH` associated constant to the `ByteObject` trait (see: https://github.com/xainag/xain-fl/pull/457/commits/fa1160f617e96e928f1bb04085346fe8b56dc3f3). This was necessary to implement the very convenient helper `ByteObject::fill_with` (see: https://github.com/xainag/xain-fl/pull/457/commits/372acd144ab7e8b7d0ec49378a2dacda5e907549)
The rest is just boring test boilerplate in `rust/src/services/tests/fetchers/mod.rs`.
Commits are independent and can be reviewed separately.
> Test the `crate::services::fetchers` module

- .github/workflows/dockerhub-master.yml
- .github/workflows/dockerhub-pr.yml
- .github/workflows/dockerhub-release.yml
Edited the logic for the `Docker Hub (PR)` workflow: only build if trigger word `#build` is found either on the PR's description (when it's first created) or if any comment is posted with such keyword, otherwise don't build an image. Comments that trigger a build automatically get a :rocket: reaction from `github-actions[bot]`.
The workflow for this is a bit cluttered, that's because a comment posted on the PR isn't associated with any branches (not even the branch where the PR is based), `master` is then assumed, so I needed to do that workaround querying GitHub's API to be able to get the PR's branch and checkout that branch to build, tag and publish the image to Docker Hub. 
---
Merges to `master` always trigger a build and the image is pushed under tags `latest` and `development`.
--- …
> PB-926 GitHub Actions for Docker Hub (PR, merges to master and tagged releases)

- configs/config.toml
- configs/docker-dev.toml
- configs/docker-release.toml
- rust/src/settings.rs
- rust/src/state_machine/coordinator.rs
- rust/src/state_machine/phases/mod.rs
- rust/src/state_machine/phases/sum.rs
- rust/src/state_machine/phases/sum2.rs
- rust/src/state_machine/phases/update.rs
- rust/src/state_machine/tests/builder.rs
The coordinator state machine currently transitions through the phases `sum` -> `update` -> `sum2` too "eagerly". It is due to the combination of
- a phase transition occurs *as soon as* "enough" messages have been processed e.g. for the `sum` phase, this is `min_sum`.
- the thresholds default (and typically are set) to the theoretical minimum e.g. for `min_sum` this is `1`.
As a result, the `sum` phase always ends with just `1` message processed, even when *many* participants have been selected to sum. The situation is similar with the `update` and `sum2` phases. Ideally, as many as possible should be able to participate, to follow the specification of the PET protocol.
This merge request introduces 2 new settings to the coordinator, to complement the existing `min_sum` and `min_update`: …
> minimum phase time

- rust/src/state_machine/tests/impls.rs
- rust/src/state_machine/tests/mod.rs
- rust/src/state_machine/tests/utils.rs
this makes the test more consistent with the unit tests we have for
the phases, and allows us to clean up the utils module of the various
`gen_xxx()` helpers.
> refactor the state machine full round test

- rust/Cargo.lock
- rust/Cargo.toml
- rust/src/lib.rs
- rust/src/services/messages/mod.rs
- rust/src/vendor/mod.rs
- rust/src/vendor/tracing_tower/mod.rs
since we need to publish xaynet soon-ish, let's vendor
`tracing-tower`. See: https://github.com/tokio-rs/tracing/issues/238
> vendor tracing-tower for now

- .github/workflows/rust.yml
Currently we build the coordinator twice in the smoke test job. The coordinator is build via docker-compose and via cargo test but we only want the latter. We use docker-compose only to run the dependencies.
> Exclude coordinator service in smoke test

- rust/src/services/messages/message_parser.rs
- rust/src/services/messages/pre_processor/mod.rs
- rust/src/services/tests/messages/message_parser.rs
- rust/src/services/tests/messages/pre_processor.rs
- rust/src/services/tests/utils.rs
- rust/src/state_machine/coordinator.rs
- rust/src/state_machine/events.rs
- rust/src/state_machine/mod.rs
- rust/src/state_machine/phases/error.rs
- rust/src/state_machine/phases/idle.rs
- rust/src/state_machine/phases/mod.rs
- rust/src/state_machine/phases/shutdown.rs
- rust/src/state_machine/phases/sum.rs
- rust/src/state_machine/phases/sum2.rs
- rust/src/state_machine/phases/unmask.rs
- rust/src/state_machine/phases/update.rs
- rust/src/state_machine/requests.rs
- rust/src/state_machine/tests/mod.rs
Instead of adding the same code at the end of each phase, we leveraged
the existing `Phase` trait. The `Phase::next` method is now split in
two parts:
```rust
trait Phase<R> {
async fn run(&mut self) -> Result<(), StateError>;
fn next(self) -> Option<StateMachine<R>>;
}
```
The `run` method runs the phase, and the `next` method just consumes
the phase to produce the next one. By separating these two bits of
logic, we can inject code right after the phase ran to completion
and before the transtion is happens:
```rust
impl<R, S> PhaseState<R, S>
where Self: Phase<R>
{
pub async fn run_phase(mut self) -> Option<StateMachine<R>> {
self.run().await.unwrap();
do_custom_stuff_common_to_all_the_phases();
self.next()
}
}
```
In our case, `do_custom_stuff_common_to_all_the_phases()` consists in …
> purge pending requests at the end of each phase

- .github/workflows/dockerhub-master.yml
After auto-deploys, we eventually run into stale replicasets, like so:
```
$ kubectl get replicasets -n development
NAME                                DESIRED   CURRENT   READY   AGE
coordinator-deployment-589486dbbd   1         1         1       15h
coordinator-deployment-6574ffcfc5   0         0         0       22h      <================ (DESIRED == 0)
coordinator-deployment-84dfcf597    0         0         0       18h      <================ (DESIRED == 0)
grafana-development-94cfff677       1         1         1       5d17h
```
The proposed addition to the CI takes care of that:
```
$ kubectl delete replicasets $(kubectl get replicasets | awk 'NR!=1 && ($2==0) {print $1}') --dry-run=client
replicaset.apps "coordinator-deployment-6574ffcfc5" deleted (dry run)
replicaset.apps …
```
> PB-925 Clean-up of stale ReplicaSets

- rust/src/services/tests/fetchers.rs
- rust/src/services/tests/messages/message_parser.rs
- rust/src/services/tests/messages/pre_processor.rs
- rust/src/services/tests/utils.rs
- rust/src/state_machine/coordinator.rs
- rust/src/state_machine/events.rs
- rust/src/state_machine/phases/error.rs
- rust/src/state_machine/phases/idle.rs
- rust/src/state_machine/phases/mod.rs
- rust/src/state_machine/phases/shutdown.rs
- rust/src/state_machine/phases/sum.rs
- rust/src/state_machine/phases/sum2.rs
- rust/src/state_machine/phases/unmask.rs
- rust/src/state_machine/phases/update.rs
- rust/src/state_machine/tests/builder.rs
- rust/src/state_machine/tests/mod.rs
- rust/src/state_machine/tests/utils.rs
this started as a small improvement: instead of repeating the same
snippet for each phase, we wanted to do it once in
`PhaseState<R,S>::run_phase()`:
```rust
pub async fn run_phase(mut self) -> Option<StateMachine<R>> {
let phase = <Self as Phase<R>>::NAME;
self.coordinator_state.events.broadcast_phase(phase); // <-- add this
self.run().await.unwrap();
self.purge_outdated_requests().unwrap();
self.next()
}
```
It turns out that this doesn't work for the idle phase, because the
round ID is updated in the `run()` implementation, _after_ the phase
event is broadcasted. Therefore, the event that is emitted has the
wrong round id.
There are multiple solutions:
1. re-emit an event in the idle phase. That may work but that means
there's a small interval of time during which the listeners still …
> automatically send the phase event before the phase starts

- configs/config.toml
- configs/docker-dev.toml
- configs/docker-release.toml
- k8s/coordinator/development/config.toml
- rust/src/bin/main.rs
- rust/src/settings.rs
Adds a settings struct for `[metrics.influxdb]` settings
```rust
pub struct InfluxSettings {
/// The URL where InfluxDB is running.
///
/// # Examples
///
/// **TOML**
/// ```text
/// [metrics.influxdb]
/// url = "http://localhost:8086"
/// ```
///
/// **Environment variable**
/// ```text
/// XAYNET_METRICS__INFLUXDB__URL=http://localhost:8086
/// ```
pub url: String,
/// The InfluxDB database name.
///
/// # Examples
///
/// **TOML**
/// ```text
/// [metrics.influxdb]
/// db = "test"
/// ```
///
/// **Environment variable**
/// ```text
/// XAYNET_METRICS__INFLUXDB__DB=test
/// ```
pub db: String,
}
```
> metrics settings

- rust/Cargo.toml
- rust/src/lib.rs
- rust/src/metrics/mod.rs
- rust/src/metrics/models.rs
First part of the `Implement data collection to InfluxDB` task.
This PR focus on the definition of the influx data models and the implementation of the metrics service + sender. The integration of the metrics service into the state machine is addressed in a separate PR.  
**metrics/mod.rs**
The `mod.rs` file contains the `MetricsService`, the `MetricsSender` and the functions to generate metrics. 
The `MetricsSender` communicates with the `MetricsService` via an unbounded channel. The unbounded channel 
accepts the type `WriteQuery`. The `WriteQuery` is a struct of the `influxdb` crate. 
My actual plan was to build a wrapper around that struct like:
```rust
enum Metric {
RoundTotalNumber(RoundTotalNumber);
Phase(Phase);
}
receiver: UnboundedReceiver<Metric>,
```
However, the …
> add metrics service

- rust/src/settings.rs
- rust/src/state_machine/mod.rs
- the `PhaseEvent` -> `PhaseName` renaming was introduced in
https://github.com/xaynetwork/xaynet/pull/469 but the documentation
wasn't updated accordingly
- some links were also broken in the `PetSettings` documentation
> fix broken links in documentation

- rust/src/state_machine/coordinator.rs
- rust/src/state_machine/mod.rs
- rust/src/state_machine/phases/error.rs
- rust/src/state_machine/phases/idle.rs
- rust/src/state_machine/phases/mod.rs
- rust/src/state_machine/phases/shutdown.rs
- rust/src/state_machine/phases/sum.rs
- rust/src/state_machine/phases/sum2.rs
- rust/src/state_machine/phases/unmask.rs
- rust/src/state_machine/phases/update.rs
- rust/src/state_machine/requests.rs
- rust/src/state_machine/tests/builder.rs
- rust/src/state_machine/tests/utils.rs
The implantation of the suggestion in #488
If everyone likes it I would merge this pr first. It will save me a lot of `#[cfg(feature = "metrics")]` annotations in #488 :)
> Move coordinator state and I/O into the Shared struct

- .github/workflows/dockercompose-validation.yml
- .github/workflows/dockerfile-validation.yml
- .github/workflows/dockerhub-master.yml
- .github/workflows/dockerhub-pr.yml
- .github/workflows/dockerhub-release.yml
- .github/workflows/kubernetes-manifests.yml
- .github/workflows/rust-audit-cron.yml
- .github/workflows/rust-audit-pr.yml
- rust/examples/test-drive-net.rs
- rust/src/client/api/http.rs
- rust/src/client/api/in_memory.rs
- rust/src/client/api/mod.rs
- rust/src/client/mobile_client/client.rs
- rust/src/client/mobile_client/mod.rs
- rust/src/client/mod.rs
- rust/src/client/request.rs
- rust/src/examples.rs
- rust/src/sdk/api.rs
- rust/src/services/mod.rs
The trait has two implementors:
- `InMemoryApiClient` that queries the coordinator services via
in-memory channels
- `HttpApiClient` that queries the coordinator services via HTTP
The second commit renames `crate::client::request` into `create::client::api`.
> Replace `Proxy` by the `ApiClient` trait

- .github/codecov.yml
As explained [here](https://docs.codecov.io/docs/commit-status#disabling-a-status).
> Disable patch checks for codecov

- rust/examples/mobile-client.rs
- rust/xaynet-client/src/mobile_client/client.rs
- rust/xaynet-client/src/mobile_client/mod.rs
Summary:
- remove `unwrap` in places where it is not safe to`unwrap`
> Add mobile client error handling

- .github/workflows/rust.yml
Summary:
* enabled the flag `--no-deps`  to disable the building of documentation for dependencies
Reduced time for cargo-doc step from [6m 12s](https://github.com/xaynetwork/xaynet/runs/1050319005?check_suite_focus=true) to [4m 5s](https://github.com/xaynetwork/xaynet/runs/1050409094?check_suite_focus=true)
> CI cargo-docs improvement

- rust/xaynet-client/src/lib.rs
- rust/xaynet-client/src/mobile_client/client.rs
- rust/xaynet-client/src/mobile_client/participant/sum.rs
- rust/xaynet-client/src/mobile_client/participant/sum2.rs
- rust/xaynet-client/src/mobile_client/participant/update.rs
- rust/xaynet-client/src/participant.rs
- rust/xaynet-core/src/message/message.rs
- rust/xaynet-server/src/services/tests/utils.rs
- rust/xaynet-server/src/state_machine/phases/sum.rs
- rust/xaynet-server/src/state_machine/phases/sum2.rs
- rust/xaynet-server/src/state_machine/phases/update.rs
- rust/xaynet-server/src/state_machine/tests/mod.rs
This key is actually necessary for security reasons (see [0] Donald
T. Davis, "Defective Sign & Encrypt in S/MIME, PKCS#7, MOSS, PEM, PGP,
and XML.", Proc. Usenix Tech. Conf. 2001 (Boston, Mass., June 25-30,
2001))
However we still need to implement these checks in the coordinator
[0]: http://world.std.com/~dtd/#sign_encrypt
> re-introduce the coordinator public key in the message header

- rust/examples/mobile-client.rs
- rust/xaynet-client/src/mobile_client/client.rs
- rust/xaynet-client/src/mobile_client/mod.rs
- rust/xaynet-client/src/mobile_client/participant/awaiting.rs
- rust/xaynet-client/src/mobile_client/participant/mod.rs
- rust/xaynet-client/src/mobile_client/participant/sum2.rs
- rust/xaynet-client/src/mobile_client/participant/update.rs
Summary:
- expose current state of the client
- make scalar configurable
> Expose current state of the client & make scalar configurable 

- .github/workflows/rust.yml
- rust/Cargo.lock
- rust/xaynet-server/Cargo.toml
* our current cache is broken (is tries to caches the folder `target` but our rust `target` folder is in `rust/target`)
The fix includes:
* update `cache` to `v2`
* enable cache for all rust jobs
* fix `target` path
* upgrading chrono to `0.4.15`. The key of the cache (the version) is the hash of the Cargo.lockfile, I had to create a new key cache key so I updated chrono to change the Cargo.lockfile
with a working cache each job takes round about [1 minute](https://github.com/xaynetwork/xaynet/runs/1081701622?check_suite_focus=true)
> Fix cache in CI

- configs/config.toml
- configs/docker-dev.toml
- configs/docker-release.toml
- k8s/coordinator/development/config.toml
- rust/xaynet-server/src/settings.rs
- rust/xaynet-server/src/state_machine/coordinator.rs
- rust/xaynet-server/src/state_machine/phases/sum2.rs
- rust/xaynet-server/src/state_machine/phases/update.rs
- rust/xaynet-server/src/state_machine/tests/builder.rs
- rust/xaynet-server/src/state_machine/tests/mod.rs
- rust/xaynet-server/src/state_machine/tests/utils.rs
Previously, the coordinator used an `expected_participants` parameter (for the expected number of participants) to calculate the model scalar. Now that scalars are determined by the participants (as part of the [generalised scalar extension](#496 )), this parameter is no longer needed.
> remove expected-participants parameter

- configs/config.toml
- configs/docker-dev.toml
- configs/docker-release.toml
- k8s/coordinator/development/config.toml
- rust/Cargo.lock
- rust/xaynet-server/Cargo.toml
- rust/xaynet-server/src/bin/main.rs
- rust/xaynet-server/src/settings.rs
Summary:
* makes the Redis URL available in the config files
> Add redis settings

- .github/workflows/rust.yml
Summary:
* enabled integration tests in ci
(to mark a test as "integration test" you have to add the prefix integration to the function name e.g. integration_set_and_get_coordinator_state)
> enable integration tests in CI

- .github/workflows/rust.yml
- rust/Cargo.lock
- rust/xaynet-server/Cargo.toml
Summary:
* included integration tests in test coverage
I had to add the dev-dependency `serial_test` to make this work because running tarpaulin with the flag `--test-threads=1` can cause a [segfault](https://github.com/xd009642/tarpaulin/issues/317).
`serial_test` guarantees that tests which are annotated with `#[serial]` are executed in serial. 
This even improves our test setup as we can now execute both the integration tests and the unit tests with a single run of `cargo test`, with the unit tests running in parallel and the integration tests running in serial.
* merged the jobs test and smoke-test into one job
> Include integration tests in test coverage

- rust/Cargo.lock
- rust/xaynet-core/src/crypto/encrypt.rs
- rust/xaynet-core/src/mask/object/mod.rs
- rust/xaynet-core/src/mask/seed.rs
- rust/xaynet-server/Cargo.toml
- rust/xaynet-server/src/lib.rs
- rust/xaynet-server/src/state_machine/coordinator.rs
- rust/xaynet-server/src/state_machine/mod.rs
- rust/xaynet-server/src/storage/impls.rs
- rust/xaynet-server/src/storage/mod.rs
- rust/xaynet-server/src/storage/redis.rs
Summary: 
- added macros that implement `FromRedisValue` and `ToRedisArgs` for various crypto types, for the `CoordinatorState` and for the `MaskObject`
- added `redis::Client` (some methods might not be needed and will be removed after the integration into the state machine is done)
> Redis client

- k8s/coordinator/development/config.toml
- rust/xaynet-server/src/bin/main.rs
- rust/xaynet-server/src/state_machine/mod.rs
- rust/xaynet-server/src/state_machine/phases/error.rs
- rust/xaynet-server/src/state_machine/phases/idle.rs
- rust/xaynet-server/src/state_machine/phases/mod.rs
- rust/xaynet-server/src/state_machine/phases/sum.rs
- rust/xaynet-server/src/state_machine/phases/sum2.rs
- rust/xaynet-server/src/state_machine/phases/update.rs
- rust/xaynet-server/src/state_machine/tests/builder.rs
- rust/xaynet-server/src/state_machine/tests/mod.rs
- rust/xaynet-server/src/state_machine/tests/utils.rs
- rust/xaynet-server/src/storage/redis.rs
Moves the `Sum` and `Seed` dict into Redis.
I tried to split the changes into 3 commits to make it easier to review.
The error handling is kept simple as I'd love to hear your ideas before I implement anything more sophisticated.
If a Redis error occurs during the message processing, we ignore the message.
- [Sum message](https://github.com/xaynetwork/xaynet/pull/519/files#diff-a07f40c3b4b740367f7d4a72897eb2d0R135)
- [Update message](https://github.com/xaynetwork/xaynet/pull/519/files#diff-b15272399ff491c84d93d4ca104eaab1R229)
If a Redis error occurs during the message processing, we ignore the message.
If a Redis error occurs when writing / reading the state that relates to the state machine itself (e.g. `get_seed_dict`, `set_coordinator_state`), we move into the error state.
- …
> Redis integration

- rust/xaynet-core/src/message/message.rs
@Robert-Steiner noticed that the test-drive example was broken, because the messages were rejected by the message parser service in the update phase. The reason is that the tag field in the update and sum2 messages was set to `1` which is for sum messages. The first commit fixes this. The second commit make `Message::to_bytes` a little more typesafe by relying the `Message.payload` field instead of `Message.tag` when possible.
> Fix message serialization

- rust/xaynet-client/src/mobile_client/participant/sum2.rs
- rust/xaynet-client/src/mobile_client/participant/update.rs
- rust/xaynet-client/src/participant.rs
- rust/xaynet-core/src/mask/masking.rs
- rust/xaynet-core/src/mask/mod.rs
- rust/xaynet-core/src/mask/object/mod.rs
- rust/xaynet-core/src/mask/object/serialization.rs
- rust/xaynet-core/src/mask/seed.rs
- rust/xaynet-core/src/message/payload/sum2.rs
- rust/xaynet-core/src/message/payload/update.rs
- rust/xaynet-server/src/state_machine/coordinator.rs
- rust/xaynet-server/src/state_machine/phases/sum2.rs
- rust/xaynet-server/src/state_machine/phases/unmask.rs
- rust/xaynet-server/src/state_machine/phases/update.rs
- rust/xaynet-server/src/state_machine/requests.rs
- rust/xaynet-server/src/state_machine/tests/utils.rs
- rust/xaynet-server/src/storage/impls.rs
- rust/xaynet-server/src/storage/redis.rs
The changes introduced for the [generalised scalar extension](#496) had the unfortunate side effect of adding unwelcome duplication to the code base - effectively, a pair of `MaskObject`s were passed through the system, either a (masked model, masked scalar) pair, or their corresponding masks. This in turn lead to the need for a pair of `Aggregation`s, a pair of `MaskDict`s, and so on. Worse, one is a vector and the other is a scalar, but the types don't reflect this at all.
This merge request introduces a new, more type-safe `MaskObject`:
```rust
pub struct MaskObject {
pub vector: MaskMany,
pub scalar: MaskOne,
}
```
consisting of a `MaskMany` (the new name for the _old_ `MaskObject`) and a `MaskOne` (containing exactly one data value):
```rust
pub struct MaskOne {
pub data: BigUint, …
```
> refactor MaskObject into vector and scalar parts

- .github/workflows/rust.yml
Sometimes a CI job gets stuck and runs until the default timeout of [360 minutes](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) is reached. This leads to our ci workers being unnecessarily blocked. This PR reduces the timeout to 20 min.
long running jobs:
- [16m](https://github.com/xaynetwork/xaynet/actions/runs/255776137)
- [4h 53m 12s](https://github.com/xaynetwork/xaynet/actions/runs/260711801)
- [2h 40m 16s](https://github.com/xaynetwork/xaynet/actions/runs/255577029)
> Reduce timeouts in CI jobs

- rust/Cargo.lock
- rust/xaynet-server/Cargo.toml
- rust/xaynet-server/src/state_machine/mod.rs
- rust/xaynet-server/src/state_machine/phases/update.rs
- rust/xaynet-server/src/storage/impls.rs
- rust/xaynet-server/src/storage/mod.rs
- rust/xaynet-server/src/storage/redis.rs
- rust/xaynet-server/src/storage/tests/mod.rs
**Summary**
- added lua script for seed update operation
- added `SeedDictUpdateError`
- refactored `DeleteSumParticipant`(I will adjust `AddSumParticipant` in a separate pr)
- increased test coverage for redis client
- annotated unused client methods with `#[cfg(test)]` (they are still useful for testing)
> Redis script for seed update operation

- configs/config.toml
- configs/docker-dev.toml
- configs/docker-release.toml
- rust/Cargo.lock
- rust/examples/Cargo.toml
- rust/examples/mobile-client.rs
- rust/examples/test-drive-net.rs
- rust/xaynet-client/Cargo.toml
- rust/xaynet-client/src/api/http.rs
- rust/xaynet-client/src/lib.rs
- rust/xaynet-client/src/mobile_client/mod.rs
- rust/xaynet-ffi/Cargo.toml
- rust/xaynet-ffi/src/lib.rs
- rust/xaynet-server/Cargo.toml
- rust/xaynet-server/src/bin/main.rs
- rust/xaynet-server/src/examples.rs
- rust/xaynet-server/src/lib.rs
- rust/xaynet-server/src/rest.rs
- rust/xaynet-server/src/settings.rs
Optional TLS server authentication:
- enable TLS on server and client side, make certificates optional (i.e. http if no certs are provided and https if certs are provided)
- update the ffi code for the mobile client
- update the server and client examples (trivially without certs for now)
- add some error handling on client initialization
- make certificate inputs configurable via paths for server and client
- gate the certificates behind a `tls` feature flag
We need to generate some actual certificates to run this stuff in a testing session, but there is a separate ticket for that.
> XN-904 tls server auth

- k8s/coordinator/development/cert-volume-mount.yaml
- k8s/coordinator/development/kustomization.yaml
This mounts the letsencrypt certificate (key and crt) into `/app/ssl/tls.key` and `/app/ssl/tls.crt`, respectively.
Whenever the letsencrypt certificates are renewed, the files inside the container are automatically updated.
> XN-1146 Setup SSL certificate data in Kubernetes

- rust/xaynet-server/src/state_machine/mod.rs
- rust/xaynet-server/src/state_machine/phases/sum.rs
- rust/xaynet-server/src/storage/impls.rs
- rust/xaynet-server/src/storage/mod.rs
- rust/xaynet-server/src/storage/redis.rs
A small PR that aligns the sum participant result with the `SeedDictUpdate` result. 
Next sprint, I would like to rethink the error handling in the state machine and maybe change it because the error handling slowly becomes a bit confusing.
> Refactor add sum participant result

- rust/xaynet-core/src/mask/masking.rs
- rust/xaynet-core/src/mask/object/serialization.rs
- rust/xaynet-core/src/mask/seed.rs
#524 introduced various changes to tidy the API especially around the generalised scalar extension. As such, the masking tests (several hundred tests generated by the macros `test_masking`, `test_aggregation` and `test_masking_and_aggregation`) now cover the (un)masking and aggregation of the scalar as well.
An issue was discovered in #524 where the unmasked scalar sum appeared larger than expected. This lead to "closeness checks" of model weights to exceed the desired tolerance, and so those tests (at least, those based on `test_masking` and `test_masking_and_aggregation`) were temporarily relaxed. This PR contains a fix for that issue, which was due to an inconsistency in the use of the PRNG in masking vs unmasking.
All masking tests are now reinstated, although a related issue has been …
> fix extended coverage of masking tests

- k8s/coordinator/base/deployment.yaml
This makes both available via MINIO_ACCESS_KEY and MINIO_SECRET_KEY env variables, respectively.
> XN-1207 Expose MinIO accessKey and secretKey to the coordinator pod

- .github/workflows/rust.yml
Removes the `--exclude-files` flag from the `cargo-tarpaulin` command. The excluded files do not exist anymore.
> Remove exclude-files flag

- rust/Cargo.lock
- rust/xaynet-client/Cargo.toml
- rust/xaynet-client/src/lib.rs
- rust/xaynet-client/src/mobile_client/participant/mod.rs
- rust/xaynet-client/src/utils/mod.rs
- rust/xaynet-client/src/utils/multipart/encoder.rs
- rust/xaynet-client/src/utils/multipart/mod.rs
- rust/xaynet-core/src/crypto/sign.rs
- rust/xaynet-core/src/mask/mod.rs
- rust/xaynet-core/src/message/payload/mod.rs
The two commits can and should probably be reviewed separately.
The `MessageEncoder` is an iterator that takes a message payload of   
type `Payload::{Sum,Update,Sum2}`, and yields serialized and signed   
messages.                                                             
Given a maximum payload length, the encoder automatically chunks the  
messages that are too big. For payloads that are small enough to fix  
in a single message, the iterator only yields one item. For payload   
that needs to be split in several messages, the encoder yields several
items.                                                                
Thus, it offers a common serialization interface for both multipart   
and non-multipart messages.
> Implement `MessageEncoder`

- rust/xaynet-client/src/mobile_client/client.rs
- rust/xaynet-client/src/mobile_client/participant/sum.rs
- rust/xaynet-client/src/mobile_client/participant/sum2.rs
- rust/xaynet-client/src/mobile_client/participant/update.rs
- rust/xaynet-client/src/utils/multipart/mod.rs
This is a minimalistic implementation of multipart messages for the mobile client. The following limitations will be addressed in follow-up PRs:
- there is no retry mechanism. If a chunk cannot be sent, the client doesn't try to re-send it.
- chunks are sent sequentially. We could make it possible to send several chunks in parallel
- if a chunk cannot be sent, the client doesn't try to send the next chunks
- the maximum chunk size is currently hard-coded
This is based on https://github.com/xaynetwork/xaynet/pull/543
> Mobile client multipart

- rust/xaynet-client/src/utils/multipart/encoder.rs
- rust/xaynet-core/src/mask/masking.rs
- rust/xaynet-core/src/mask/mod.rs
- rust/xaynet-core/src/mask/object/mod.rs
- rust/xaynet-core/src/mask/object/serialization.rs
- rust/xaynet-core/src/mask/object/serialization/mod.rs
- rust/xaynet-core/src/mask/object/serialization/vect.rs
- rust/xaynet-core/src/mask/seed.rs
- rust/xaynet-core/src/message/payload/sum2.rs
- rust/xaynet-core/src/message/payload/update.rs
- rust/xaynet-server/src/state_machine/phases/sum2.rs
- rust/xaynet-server/src/storage/tests/mod.rs
This merge request implements some minor refactoring for further improvements to the mask object.
- Renames throughout for more consistency. In particular, `MaskMany` and `MaskOne` are renamed `MaskVect` and `MaskUnit`, respectively, as are the accessor fields
```rust
pub struct MaskObject {
pub vect: MaskVect,
pub unit: MaskUnit,
}
```
- Reorganised `mask/object/serialization.rs` into
```
- mask
- object
- serialization
- mod.rs
- vect.rs
- unit.rs // in a separate PR
```
for a cleaner separation of the serialization code for mask object and its constituents. Also acts as a precursor to more improvements to mask unit serialization, which will be in `unit.rs` in another PR.
- Removed unnecessary "scalar accessor" code in the `Sum2Buffer` and `UpdateBuffer`. The sum2 and update payloads …
> mask object and unmasking improvements

- rust/xaynet-client/src/utils/multipart/encoder.rs
- rust/xaynet-core/src/mask/object/serialization/mod.rs
- rust/xaynet-core/src/mask/object/serialization/unit.rs
- rust/xaynet-core/src/mask/object/serialization/vect.rs
- rust/xaynet-core/src/message/payload/sum2.rs
- rust/xaynet-core/src/message/payload/update.rs
- rust/xaynet-core/src/testutils/messages.rs
- rust/xaynet-core/src/testutils/multipart.rs
Currently, `MaskUnit`s are serialized by first converting to a `MaskVect`. This merge request allows mask units to be serialized _directly_. In line with other unit/scalar types, a `MaskUnitBuffer` is introduced serving the usual purpose as a helper for (de)serializing the corresponding `MaskUnit`. As a result of a more specialised serialization, mask units can be encoded more compactly by excluding the `LENGTH` field, as the data is always a single value.
TODO.
> more compact serialized mask unit

- rust/xaynet-server/src/settings.rs
- rust/xaynet-server/src/storage/mod.rs
- rust/xaynet-server/src/storage/s3.rs
- rust/xaynet-server/src/storage/tests/mod.rs
**Summary**
- added s3 client
- added tests
As I already mentioned it would be nice to have an API that is similar to the redis client. For example, in the s3 client we don't have a limit on concurrent requests because currently we only write the global model at the end of the round.
However, if we also want to persist the local models, we will definitely need that.
In addition, it would be nice to define traits that are implemented by the clients so that we use the traits in the state machine instead of the concrete types. That would give us the ability to for example easily swap out the Redis client for in-memory storage (as we had before).
As with the redis client, the s3 client also has no functionality for retries and timeouts because we decided to solve it later. In my opinion, we …
> S3 client implementation

- README.md
The command shown in the README file does not work because the wrong configuration is used.
`config.toml` uses uses `localhost` as `bind_address` and therefore the coordinator can be reached within the container itself, but not from the host system.
> Use docker-dev.toml instead of config.toml

- .github/workflows/rust.yml
Moves the bench step into a separate job to decrease ci time
> move bench to a separate job

- rust/xaynet-client/src/lib.rs
- rust/xaynet-core/src/lib.rs
- rust/xaynet-core/src/message/utils/chunkable_iterator.rs
- rust/xaynet-ffi/src/lib.rs
- rust/xaynet-macros/src/lib.rs
- rust/xaynet-server/src/lib.rs
- rust/xaynet-server/src/state_machine/mod.rs
- rust/xaynet/src/lib.rs
**References**
- [XN-1178](https://xainag.atlassian.net/browse/XN-1178)
**Summary**
The `cargo doc` respectively `rustdoc` seems not to provide an option like `--deny warnings` as for example in `clippy`. Therefore we can't simply attach this to the CI command, but have to specify it in code. `forbid` was chosen over `deny` to avoid `allow`ing locally by accident. The dead documentations links have been fixed as well.
> XN-1178 doc forbid warnings

- .github/workflows/rust.yml
- rust/Cargo.toml
- rust/benches/Cargo.toml
- rust/examples/Cargo.toml
- rust/examples/mobile-client.rs
- rust/xaynet-client/Cargo.toml
- rust/xaynet-client/src/mobile_client/participant/awaiting.rs
- rust/xaynet-core/Cargo.toml
- rust/xaynet-core/src/mask/model.rs
- rust/xaynet-core/src/message/payload/update.rs
- rust/xaynet-ffi/Cargo.toml
- rust/xaynet-macros/Cargo.toml
- rust/xaynet-server/Cargo.toml
- rust/xaynet-server/src/services/messages/multipart/service.rs
- rust/xaynet-server/src/services/tests/utils.rs
- rust/xaynet-server/src/state_machine/phases/idle.rs
- rust/xaynet-server/src/state_machine/phases/sum2.rs
- rust/xaynet-server/src/state_machine/phases/unmask.rs
- rust/xaynet-server/src/state_machine/phases/update.rs
- rust/xaynet-server/src/state_machine/tests/builder.rs
- rust/xaynet-server/src/state_machine/tests/impls.rs
- rust/xaynet-server/src/state_machine/tests/mod.rs
- rust/xaynet-server/src/state_machine/tests/utils.rs
- rust/xaynet-server/src/storage/redis.rs
- rust/xaynet-server/src/storage/s3.rs
- rust/xaynet-server/src/storage/tests/mod.rs
- rust/xaynet/Cargo.toml
**References**
- [XN-1132](https://xainag.atlassian.net/browse/XN-1132)
**Summary**
Enables `cargo clippy` for all targets (including tests) on the CI and fixes the newly raised issues. Also enables `clippy::cargo` lints, those are off by default and check some best practices for the `Cargo.toml` files. Fixed the issues within the `package` section and reordered them in the same way as the rust book. Also took the opportunity to sort the dependencies alphanumerically to improve findability (if the sorting is deemed too much, i can also revert this).
**Todo**
> XN-1132 enable clippy everywhere

- README.md
- README.tpl
- rust/Cargo.toml
- rust/benches/Cargo.toml
- rust/examples/Cargo.toml
- rust/xaynet-client/Cargo.toml
- rust/xaynet-core/Cargo.toml
- rust/xaynet-ffi/Cargo.toml
- rust/xaynet-macros/Cargo.toml
- rust/xaynet-server/Cargo.toml
- rust/xaynet/Cargo.toml
**References**
- [XN-1263](https://xainag.atlassian.net/browse/XN-1263)
**Summary**
The rfc on a minimal supported rust version is far from being stablilized, see the [tracking issue](https://github.com/rust-lang/rust/issues/65262). Therefore we at least include this as metadata information and in the readme.
> XN-1263 add minimum supported rust version

- rust/xaynet-client/src/mobile_client/participant/sum2.rs
- rust/xaynet-client/src/mobile_client/participant/update.rs
- rust/xaynet-client/src/participant.rs
- rust/xaynet-core/src/mask/config/mod.rs
- rust/xaynet-core/src/mask/masking.rs
- rust/xaynet-core/src/mask/mod.rs
- rust/xaynet-core/src/mask/object/mod.rs
- rust/xaynet-core/src/mask/seed.rs
- rust/xaynet-server/src/state_machine/phases/sum2.rs
- rust/xaynet-server/src/state_machine/phases/update.rs
- rust/xaynet-server/src/storage/tests/mod.rs
Implements an overdue suggestion https://github.com/xaynetwork/xaynet/pull/524#discussion_r490779866 to introduce a struct collecting both a vector `MaskConfig` and a unit `MaskConfig` together:
```rust
pub struct MaskConfigPair {
pub vect: MaskConfig,
pub unit: MaskConfig,
}
```
This helps to tidy the API in several places, namely
- `Masker`
- `Aggregation`
- `MaskSeed`
- `MaskObject`
all of which currently take two `MaskConfig`s as parameters in their methods. In addition, as most of the code currently uses the same config for both anyway, a `From` impl helps to further reduce code duplication.
> masking configuration pair

- .github/workflows/dockerhub-pr-with-parameters.yml
Add action: `docker/setup-buildx-action@v1` 
To fix: 
```
auto-push is currently not implemented for docker driver
Error: buildx call failed with: auto-push is currently not implemented for docker driver
```
> XN-1209 Add action docker/setup-buildx-action@v1 to fix: buildx call

- rust/xaynet-server/src/state_machine/phases/mod.rs
- rust/xaynet-server/src/state_machine/phases/sum.rs
- rust/xaynet-server/src/state_machine/phases/sum2.rs
- rust/xaynet-server/src/state_machine/phases/update.rs
- rust/xaynet-server/src/state_machine/requests.rs
Addresses an issue where a message may be dropped after the delay has elapsed.
Found the solution in the [tokio::select! documentation](https://docs.rs/tokio/0.2.22/tokio/macro.select.html#avoid-racy-if-preconditions). 
We should check later if we have the same error in phase timeout.
> fix dropping message in select branch

- rust/xaynet-core/src/mask/masking.rs
**Summary.**
This PR adds to the existing suite of masking / aggregation tests, to more thoroughly test the generalised scalar (e.g. there had been no test for scalars taking arbitrary values > 1).
More specifically,
- a new suite of tests `test_masking_scalar!` (to complement `test_masking!`) which samples a random scalar. 
- a new suite of tests `test_masking_and_aggregation_scalar!` (to complement `test_masking_and_aggregation!`) which samples random scalars.
- `test_aggregation!` is extended slightly, to additionally sample a random mask unit. `test_masking!` and `test_masking_and_aggregation!` are largely unchanged.
**Explanation of the sense in which the new tests _complement_ the existing.** 
The structure of `test_masking_scalar!` largely follows the existing `test_masking!`. The …
> randomized scalar tests

- rust/Cargo.lock
- rust/xaynet-server/Cargo.toml
- rust/xaynet-server/src/state_machine/mod.rs
- rust/xaynet-server/src/storage/api.rs
- rust/xaynet-server/src/storage/impls.rs
- rust/xaynet-server/src/storage/mod.rs
- rust/xaynet-server/src/storage/redis.rs
- rust/xaynet-server/src/storage/store.rs
- rust/xaynet-server/src/storage/tests/mod.rs
**Summary**
- added a `CoordinatorStorage`and a `ModelStorage` trait 
The reason why I chose these names instead of `VolatileStorage` and `PersistentStorage` is that the coordinator state also has values ​​that have to be persistence like the `round_id`. 
- refactored pet wrappers
- added a generic store
> Impl storage traits

- .github/workflows/rust.yml
The new release of tarpaulin `v0.17.0` causes segfaults when running our tests.
I don't know yet what the problem is. This pr changes the version back to tarpaulin `v0.16.0`
> use tarpaulin version 0.16

- rust/Cargo.lock
- rust/xaynet-sdk/Cargo.toml
- rust/xaynet-sdk/src/state_machine/io.rs
- rust/xaynet-sdk/src/state_machine/mod.rs
- rust/xaynet-sdk/src/state_machine/phases/new_round.rs
This first unit test paves the way for writing unit tests for all the
state machine. The crux of it is the `MockIO` type that can be used to
avoid simulating a coordinator.
> add Phase<NewRound> test

- .github/workflows/rust.yml
Adds the version of rustc to the cache key. As soon as a new rust version is available, a new cache is created instead of using the old one. Without the rustc version, the old cache would be used and the dependencies would be constantly recompiled.
> add rustc version to cache key

- rust/Cargo.lock
- rust/xaynet-server/Cargo.toml
our changes have been merged to `warp`, so we can depend on it again (and remove our fork). once they release a new version to crates.io, we can change to the registry as well.
> Update warp dependency

- rust/xaynet-mobile/src/ffi/participant.rs
- rust/xaynet-mobile/tests/ffi_test.c
- rust/xaynet-mobile/xaynet_ffi.h
Dart ffi currently does not support passing structs by value
releated issues:
- https://github.com/dart-lang/sdk/issues/41062
- https://github.com/dart-lang/sdk/issues/36730
Therefore we change the function so that a pointer is accepted instead of a struct
This will hopfully be possible in [v1.1](https://github.com/dart-lang/sdk/projects/13#card-20672366)
> pass ByteBuffer pointer instead of struct

- .github/workflows/rust.yml
- .gitignore
- README.md
- README.tpl
- rust/Cargo.lock
- rust/Cargo.toml
- rust/benches/Cargo.toml
- rust/examples/Cargo.toml
- rust/xaynet-core/Cargo.toml
- rust/xaynet-macros/Cargo.toml
- rust/xaynet-mobile/Cargo.toml
- rust/xaynet-sdk/Cargo.toml
- rust/xaynet-server/Cargo.toml
- rust/xaynet/Cargo.toml
**References**
- [XN-1370](https://xainag.atlassian.net/browse/XN-1370)
**Summary**
- updates msrv and github workflow to use stable cargo doc
- update readme and template
- add a readme check to the workflow: use `cargo readme` to generate a readme from the code docs + template. this will notify us if the docs and the readme diverge. in consequence no changes should be made to the readme itself, but only to the docs and the template, then the readme can be generated via `cargo readme > README.md`.
> XN-1370 stable docs

- rust/xaynet-sdk/src/message_encoder/encoder.rs
- rust/xaynet-server/src/services/messages/multipart/buffer.rs
- rust/xaynet-server/src/services/messages/multipart/service.rs
There were multiple combined issues:
- a bug in the `ExactSizeIterator` implementation for `MultipartMessageBuffer`
- in `xaynet_sdk`, the chunk IDs start at 0, while the server expected
them to start at 1. The server now expects the chunk IDs to start a 0
- under certain conditions, `MessageBuilder::has_all_chunk()` would
never return `true`
- in `xaynet_sdk`, we were generating new random message IDs for each
chunks
> fix multipart messages

- rust/Cargo.lock
- rust/xaynet-mobile/Cargo.toml
- rust/xaynet-mobile/src/ffi/mod.rs
**Summary**
- set the `xaynet-mobile` as `rlib` next to the other `crate_type`s to make it usable downstream as a rust dependency
- re-export the `ffi_support` types which are used in the public api to avoid downstream version collisions by separate imports
> xaynet-mobile as rlib

- .github/workflows/rust.yml
- rust/xaynet-core/src/mask/object/serialization/unit.rs
- rust/xaynet-core/src/mask/object/serialization/vect.rs
- rust/xaynet-sdk/src/message_encoder/encoder.rs
- rust/xaynet-sdk/src/state_machine/phase.rs
- rust/xaynet-sdk/src/state_machine/phases/new_round.rs
- rust/xaynet-sdk/src/state_machine/phases/sum.rs
- rust/xaynet-sdk/src/state_machine/state_machine.rs
- rust/xaynet-sdk/src/state_machine/tests/phases/new_round.rs
- rust/xaynet-sdk/src/state_machine/tests/phases/sum.rs
- rust/xaynet-sdk/src/state_machine/tests/phases/sum2.rs
- rust/xaynet-sdk/src/state_machine/tests/phases/update.rs
- rust/xaynet-sdk/src/state_machine/tests/utils.rs
- rust/xaynet-server/src/services/messages/multipart/service.rs
- rust/xaynet-server/src/services/messages/state_machine.rs
- rust/xaynet-server/src/state_machine/phases/mod.rs
**References**
- [XN-1318](https://xainag.atlassian.net/browse/XN-1318) (addresses [#578](https://github.com/xaynetwork/xaynet/pull/578#discussion_r516009877))
**Summary**
*documentation regression:*
while working on the actual issue i noticed regression in the documentation which is not yet caught by the ci. hence:
- add doc check for all docs including private docs
- fix broken doc links
*clippy warnings for large enum variants:*
some of the state machine enum variants are quite large (up to 500-800 bytes) and some of the enums differ between the variants (200 vs 800 bytes), which caused the clippy lint. just boxing the variants leads to some negative side effects:
- boxing of subsequent fields of the variant to avoid unboxing/reboxing for our various from/into impls, which also spirals …
> XN-1318 sdk clippy warnings

- rust/Cargo.lock
- rust/benches/Cargo.toml
- rust/examples/Cargo.toml
- rust/xaynet-core/Cargo.toml
- rust/xaynet-mobile/Cargo.toml
- rust/xaynet-sdk/Cargo.toml
- rust/xaynet-server/Cargo.toml
- rust/xaynet/Cargo.toml
**References**
- [XN-1491](https://xainag.atlassian.net/browse/XN-1491)
**Summary**
- updated most of the dependencies
- the remaining dependencies are either blocked by `warp` or `tokio`, put some todos there
- the `xaynet` dependency versions have to be bumped during release
- removed the duplicate `msrv` from the `[package.metadata]`, because already present in `[workspace.metadata]`
> XN-1491 update dependencies

- .github/dependabot.yml
- README.md
- README.tpl
- rust/examples/Cargo.toml
adds and enables dependabot for:
- xaynet workspace (checks daily whether new versions of the dependencies are available)
- python bindings (weekly checks)
- dependencies of the keras example (weekly checks)
- github actions (weekly checks)
- disable binary auto discovery for `examples` (https://github.com/dependabot/dependabot-core/issues/1156)
- updated README
> add dependabot config

- rust/Cargo.lock
- rust/xaynet-server/Cargo.toml
- rust/xaynet-server/src/rest.rs
- rust/xaynet-server/src/settings/mod.rs
**References**
- [XN-1493](https://xainag.atlassian.net/browse/XN-1493)
**Summary**
temporarily change to a released version of `warp` and therefore disable server side client authentication.
> XN-1493 temp change warp to released version

- rust/xaynet-mobile/src/participant.rs
When a new round has started, the participant may no longer have an update participant therefore we reset the `should_set_model` flag on a new round event.
> Reset should_set_model on new round

- bindings/python/README.md
- bindings/python/examples/keras_house_prices/README.md
- bindings/python/examples/keras_house_prices/keras_house_prices/participant.py
- bindings/python/examples/keras_house_prices/setup.py
- bindings/python/examples/participate_in_update.py
- bindings/python/migration_guide.md
- bindings/python/xaynet_sdk/__init__.py
- bindings/python/xaynet_sdk/async_participant.py
- bindings/python/xaynet_sdk/participant.py
- added python migration guide ([rendered version](https://github.com/xaynetwork/xaynet/blob/python-migration-guide/bindings/python/migration_guide.md))
- fixed type issues in the example
- added a note that Python 3.7.1 or higher (because of pandas) is required to run the example
> add python migration guide

- rust/xaynet-server/src/state_machine/tests/mod.rs
- rust/xaynet-server/src/storage/coordinator_storage/redis/mod.rs
**References** 
- [XN-1508](https://xainag.atlassian.net/browse/XN-1508)
**Summary**
- update full round integration test of the state machine to account for less sum2 participants than sum participants
- fix some docs in the redis storage lua scripts
the extension to the min and max counts will be done in the next pr.
> XN-1508 sum participant checks

- bindings/python/Cargo.lock
- bindings/python/Cargo.toml
- bindings/python/src/python_ffi.rs
- rust/xaynet-mobile/src/settings.rs
Small pr that sets the `MaxMessageSize` to `unlimited` in the python participant.
The python bindings are primarily there to experiment with fed ml/secure aggragtion. 
So there is not need to split these messages. 
Does not fix `XN-1503` because we still need to expose this setting to the C API 
and it would be nice to make it configurable in the python participant
> set max message size to unlimited

- configs/config.toml
- configs/docker-dev.toml
- k8s/coordinator/development/config.toml
- rust/xaynet-core/src/message/message.rs
- rust/xaynet-core/src/message/mod.rs
- rust/xaynet-server/src/examples.rs
- rust/xaynet-server/src/settings/mod.rs
- rust/xaynet-server/src/settings/s3.rs
- rust/xaynet-server/src/state_machine/coordinator.rs
- rust/xaynet-server/src/state_machine/phases/sum2.rs
- rust/xaynet-server/src/state_machine/tests/builder.rs
- rust/xaynet-server/src/state_machine/tests/mod.rs
- rust/xaynet-server/src/state_machine/tests/utils.rs
**References**
- [XN-1508](https://xainag.atlassian.net/browse/XN-1508)
**Summary**
- split protocol count invariants from settings
- update docs and examples
- add sum2 time settings and update tests
- update config files
- update state machine and tests
> XN-1508 split count settings and invariants

- rust/Cargo.lock
- rust/xaynet-sdk/Cargo.toml
- rust/xaynet-sdk/src/lib.rs
- rust/xaynet-sdk/src/utils/concurrent_futures.rs
- rust/xaynet-sdk/src/utils/mod.rs
- rust/xaynet-server/Cargo.toml
This will allow clients to start sending multiple chunks concurrently.
[`FuturesUnordered`](https://docs.rs/futures-util/0.3.5/futures_util/stream/futures_unordered/struct.FuturesUnordered.html)
allows us to poll multiple futures, but if we want to really run them
_concurrently_ we need to spawn them first. So this type is just a thin
wrapper around `FuturesUnordered`.
> add a helper for running futures concurrently

- .github/workflows/rust.yml
- rust/xaynet-server/src/metrics/mod.rs
If `cargo test` is called with the `--all-target` flag, the doc tests will not be executed. (related https://github.com/rust-lang/cargo/issues/6669)
Fixes two docs tests. I've already spent some time fixing them in #636 but I didn't get it to work so I just annotated them with `ignore`.
> fix docs tests

- rust/xaynet-analytics/src/data_combination/data_combiner.rs
- rust/xaynet-analytics/src/data_combination/data_points/data_point.rs
- rust/xaynet-analytics/src/data_provision/analytics_event.rs
Refers to: [XN-1433](https://xainag.atlassian.net/browse/XN-1433)
---
It changes a bit `DataCombiner` so that it's easier to test, and adds relevant unit tests.
Since the initialisation of `DataPoints` has a common interfaces and is quite repetitive, but the implementation differs, maybe it would make sense in the future to split up this component and have one `DataCombiner` for each type of `DataPoint`, with its own configuration (metadata instances above all).
Anyway, for now i guess this is good enough, and now it has its unit tests. 
---
Follow up: [XN-1542](https://xainag.atlassian.net/browse/XN-1542) -> unit tests for each `DataPoint` type.
> add data combiner unit tests

- rust/Cargo.lock
- rust/xaynet-server/Cargo.toml
- rust/xaynet-server/src/bin/main.rs
- rust/xaynet-server/src/settings/mod.rs
- rust/xaynet-server/src/state_machine/initializer.rs
- rust/xaynet-server/src/state_machine/mod.rs
- rust/xaynet-server/src/state_machine/phases/error.rs
- rust/xaynet-server/src/state_machine/phases/idle.rs
- rust/xaynet-server/src/state_machine/phases/mod.rs
- rust/xaynet-server/src/state_machine/phases/shutdown.rs
- rust/xaynet-server/src/state_machine/phases/sum.rs
- rust/xaynet-server/src/state_machine/phases/sum2.rs
- rust/xaynet-server/src/state_machine/phases/unmask.rs
- rust/xaynet-server/src/state_machine/phases/update.rs
- rust/xaynet-server/src/state_machine/tests/builder.rs
- rust/xaynet-server/src/state_machine/tests/impls.rs
- rust/xaynet-server/src/state_machine/tests/utils.rs
- rust/xaynet-server/src/storage/coordinator_storage/redis/impls.rs
- rust/xaynet-server/src/storage/coordinator_storage/redis/mod.rs
- rust/xaynet-server/src/storage/mod.rs
- rust/xaynet-server/src/storage/store.rs
- rust/xaynet-server/src/storage/tests/mod.rs
- rust/xaynet-server/src/storage/traits.rs
- rust/xaynet-server/src/storage/trust_anchor/mod.rs
- rust/xaynet-server/src/storage/trust_anchor/noop.rs
Cherry-pick trust anchor trait + implementation into the state machine from #636
- applied review comments
> impl trust anchor trait

- rust/xaynet-server/src/rest.rs
- rust/xaynet-server/src/settings/mod.rs
**References**
- [XN-1522](https://xainag.atlassian.net/browse/XN-1522)
**Summary**
- activates server side client auth again, with stable dependency
> XN-1522 enable client auth

- rust/examples/Cargo.toml
- rust/xaynet-analytics/Cargo.toml
- rust/xaynet-analytics/src/lib.rs
- rust/xaynet-core/src/lib.rs
- rust/xaynet-mobile/src/lib.rs
- rust/xaynet-sdk/src/lib.rs
- rust/xaynet-server/src/lib.rs
- rust/xaynet/src/lib.rs
**Summary**
the current doc lints deny everything, which leads to errors on the latest nightly, like:
```
error[E0453]: allow(unused_parens) incompatible with previous forbid
--> xaynet-server/src/services/fetchers/mod.rs:79:81
|
79 |       async fn round_params(&mut self) -> Result<RoundParamsResponse, FetchError> {
|  _________________________________________________________________________________^
80 | |         poll_fn(|cx| {
81 | |             <RoundParams as Service<RoundParamsRequest>>::poll_ready(&mut self.round_params, cx)
82 | |         })
...  |
90 | |         .map_err(into_fetch_error)?)
91 | |     }
| |_____^ overruled by previous forbid
```
this specifies the lints we actually want to deny. later on we also might want to warn about missing docs, like:
```
#![cfg_attr(doc, …
```
> specify doc forbids

- rust/xaynet-server/src/metrics/mod.rs
- rust/xaynet-server/src/metrics/recorders/influxdb/dispatcher.rs
- rust/xaynet-server/src/metrics/recorders/influxdb/models.rs
- rust/xaynet-server/src/metrics/recorders/influxdb/recorder.rs
- rust/xaynet-server/src/state_machine/phases/error.rs
- rust/xaynet-server/src/state_machine/phases/idle.rs
- rust/xaynet-server/src/state_machine/phases/mod.rs
- rust/xaynet-server/src/state_machine/phases/unmask.rs
**References**
- [XN-1582](https://xainag.atlassian.net/browse/XN-1582)
**Summary**
- simplify message accepted metrics to one call differentiated by phase tags
- make most of the metrics function signatures more ergonomic to use via `Into` trait bounds
- replace custom metric/request/query conversions with `From` impls
> XN-1582 simplify metrics

- rust/xaynet-server/src/metrics/mod.rs
- rust/xaynet-server/src/state_machine/coordinator.rs
- rust/xaynet-server/src/state_machine/mod.rs
- rust/xaynet-server/src/state_machine/phases/handler.rs
- rust/xaynet-server/src/state_machine/phases/mod.rs
- rust/xaynet-server/src/state_machine/phases/sum.rs
- rust/xaynet-server/src/state_machine/phases/sum2.rs
- rust/xaynet-server/src/state_machine/phases/update.rs
**References**
- [XN-1579](https://xainag.atlassian.net/browse/XN-1579)
- ~depends on #707 and must be rebased after that is merged~
**Summary**
reduce code duplication:
- move `Handler` related code into its own module
- add a `Counter` for `Handler` impls and move default impls there
- move `process_during()`/`process_until_enough()` related code from phase-dependent `run()` to a unified `process()` method
- add some `metric!` shortcuts
> XN-1579 unify handle request

- .github/workflows/rust-audit-cron.yml
- .github/workflows/rust.yml
Didn't change it in `rust-audit-cron.yml` since there is not sane way to share the value and we shouldn't care too much about the toolchain of `cargo audit`
> Fix version of the rust toolchain

- rust/rustfmt.toml
**Summary**
`rustfmt` throws a deprecation warning in the latest `nightly` which we run on the ci:
```
Warning: the `merge_imports` option is deprecated. Use `imports_granularity=Crate` instead
```
this pr replaces the deprecated option with the new one. obviously, the new option is not known to older `rustfmt` version, hence everyone must update it locally after this pr, which can be done by:
```
rustup update nightly
rustup toolchain install nightly-2021-01-31
rustup toolchain uninstall nightly-2021-01-31
```
then `rustfmt` can be run as usual via `cargo +nightly fmt`.
the last uninstall is optional and just for toolchain cleanup. we have to install a fixed nightly version (same version as the ci uses), because `rustfmt` is not always available on the nightly channel ([see …
> fix rustfmt deprecation

- rust/Cargo.lock
- rust/xaynet-analytics/Cargo.toml
- rust/xaynet-analytics/src/controller.rs
- rust/xaynet-analytics/src/data_combination/data_combiner.rs
- rust/xaynet-analytics/src/data_combination/data_points/data_point.rs
- rust/xaynet-analytics/src/data_combination/data_points/screen_active_time.rs
- rust/xaynet-analytics/src/data_combination/data_points/screen_enter_count.rs
- rust/xaynet-analytics/src/data_combination/data_points/was_active_each_past_period.rs
- rust/xaynet-analytics/src/data_combination/data_points/was_active_past_n_days.rs
- rust/xaynet-analytics/src/database/analytics_event/data_model.rs
- rust/xaynet-analytics/src/database/analytics_event/repo.rs
- rust/xaynet-analytics/src/database/common.rs
- rust/xaynet-analytics/src/database/controller_data/data_model.rs
- rust/xaynet-analytics/src/database/controller_data/mod.rs
- rust/xaynet-analytics/src/database/controller_data/repo.rs
- rust/xaynet-analytics/src/database/isar.rs
- rust/xaynet-analytics/src/database/mod.rs
- rust/xaynet-analytics/src/database/screen_route/data_model.rs
- rust/xaynet-analytics/src/database/screen_route/repo.rs
- rust/xaynet-analytics/src/lib.rs
- rust/xaynet-analytics/src/sender.rs
[XN-1557](https://xainag.atlassian.net/browse/XN-1557)
Add `AnalyticsController` component, responsible for initialising all dependencies and expose a simple API for the mobile framework layer to utilise. 
I've added two small refactors:
1) Now `Repo` trait implementations receive the `IsarDb` instance in their `get_all` / `add` methods, because `IsarInstance` is by design a singleton that cannot be cloned.
2) Added a `SchemaGenerator` trait with a default implementation for the various data models to implement as is, so that the `CollectionSchema` can be generated directly by the `AnalyticsController`, and there's no duplication of constant collection names, nor we can forget to register at the `IsarDb` level a new collection (because it's handled by the `AnalyticsController`).
Hope …
> Implement analytics controller

- .github/workflows/rust.yml
- rust/xaynet-core/src/message/utils/chunkable_iterator.rs
- rust/xaynet-sdk/src/lib.rs
- rust/xaynet-sdk/src/state_machine/io.rs
- rust/xaynet-sdk/src/state_machine/phase.rs
- rust/xaynet-server/src/metrics/mod.rs
- rust/xaynet-server/src/metrics/recorders/influxdb/dispatcher.rs
- rust/xaynet-server/src/state_machine/tests/initializer.rs
- rust/xaynet-server/src/storage/coordinator_storage/redis/impls.rs
- rust/xaynet-server/src/storage/coordinator_storage/redis/mod.rs
- rust/xaynet-server/src/storage/model_storage/s3.rs
**Summary**
- disable integration tests by default, enable them on the ci (opt-in instead of opt-out)
- fix doc tests
currently the integration tests fail by default, meaning that they fail if the required resources are not available. i made an attempt to disable them by default such that tests can be run locally without false negatives and changed the ci to run all of them.
unfortunately the `#[ignore]` for tests is binary, having configurable flags would be nice (could be done with feature flags, but this would pollute the features namespace on the other hand). anyways, ignored tests can be run locally or on the ci with `cargo test -- --ignored` or all tests can be run with `cargo test -- -Z unstable-options --include-ignored` (the latter is only marked unstable because it doesn't work …
> integration tests flag

- rust/Cargo.lock
updates sub dependencies via `cargo update -p nb-connect -p hyper`
main reason for this pr is to update `hyper` and `nb-connect`
```
Crate:         hyper
Version:       0.14.2
Title:         Multiple Transfer-Encoding headers misinterprets request payload
Date:          2021-02-05
ID:            RUSTSEC-2021-0020
URL:           https://rustsec.org/advisories/RUSTSEC-2021-0020
Solution:      Upgrade to >=0.14.3 OR >=0.13.10, <0.14.0
Dependency tree: 
hyper 0.14.2
├── warp 0.3.0
│   └── xaynet-server 0.2.0
│       └── xaynet 0.11.0
├── rusoto_signature 0.46.0
│   └── rusoto_core 0.46.0
│       ├── xaynet-server 0.2.0
│       └── rusoto_s3 0.46.0
│           └── xaynet-server 0.2.0
├── rusoto_credential 0.46.0
│   ├── rusoto_signature 0.46.0
│   └── rusoto_core 0.46.0
├── rusoto_core 0.46.0 …
```
> update hyper and nb-connect

- .github/workflows/rust.yml
Set `env.RUST_STABLE` as default toolchain. without `default: true` cargo 1.50 is used
> set toolchain default

- rust/xaynet-analytics/src/controller.rs
- rust/xaynet-analytics/src/data_combination/data_combiner.rs
- rust/xaynet-analytics/src/data_combination/data_points/data_point.rs
- rust/xaynet-analytics/src/data_combination/data_points/screen_active_time.rs
- rust/xaynet-analytics/src/data_combination/data_points/screen_enter_count.rs
- rust/xaynet-analytics/src/data_combination/data_points/was_active_each_past_period.rs
- rust/xaynet-analytics/src/data_combination/data_points/was_active_past_n_days.rs
- rust/xaynet-analytics/src/database/analytics_event/adapter.rs
- rust/xaynet-analytics/src/database/analytics_event/data_model.rs
- rust/xaynet-analytics/src/database/analytics_event/mod.rs
- rust/xaynet-analytics/src/database/analytics_event/repo.rs
- rust/xaynet-analytics/src/database/common.rs
- rust/xaynet-analytics/src/database/controller_data/adapter.rs
- rust/xaynet-analytics/src/database/controller_data/data_model.rs
- rust/xaynet-analytics/src/database/controller_data/mod.rs
- rust/xaynet-analytics/src/database/controller_data/repo.rs
- rust/xaynet-analytics/src/database/isar.rs
- rust/xaynet-analytics/src/database/screen_route/adapter.rs
- rust/xaynet-analytics/src/database/screen_route/data_model.rs
- rust/xaynet-analytics/src/database/screen_route/mod.rs
- rust/xaynet-analytics/src/database/screen_route/repo.rs
- rust/xaynet-analytics/src/sender.rs
[XN-1642](https://xainag.atlassian.net/browse/XN-1642)
Add and implement get and get_all methods, with reading objects from the db.
It also refactors a bit `AnalyticsController`, the data models and the fact that now `Repo` is just a trait on the data models. 
It also adds the `RelationalField` abstraction to be able to save and retrieve instances of data models as fields of other data models (one of the fields of `AnalyticsEvent` is `ScreenRoute`).
It's very likely that some of this could be more efficient, but I struggled a bit with ownerships.
> implement read and get methods + refactor

- bindings/python/Cargo.lock
- bindings/python/Cargo.toml
- rust/Cargo.lock
- rust/examples/Cargo.toml
- rust/xaynet-mobile/Cargo.toml
- rust/xaynet-mobile/README.md
- rust/xaynet-mobile/build.rs
- rust/xaynet-mobile/cbindgen.toml
- rust/xaynet-sdk/Cargo.toml
- rust/xaynet-server/Cargo.toml
**Summary**
- pin `cbindgen` version: this requires `cbindgen` to be a dev-dependency instead of a command line tool, which in turn requires us to use a build script. a nice side effect is that we can now run it in stable instead of nightly (the nightly `[parse.expand]` option wasn't actually necessary because we wrap the macros and therefore never expose them as part of the ffi api; the generated header file stays the same).
- pin `pyo3` version
- update dependencies: some of them seem to have slipped through dependabot's watch
- rebuild the lock files: all sub-dependencies are up to date now and `cargo update -w` doesn't make any further updates
> Pin bindgen dependencies

- .github/workflows/dockerhub-cleanup.yml
The idea is to have this running every week and getting rid of these inactive tags we have on Docker Hub:
I've also made this possible to trigger via a `workflow_dispatch` event, so we can run it whenever we want.
You'll notice that my commit history changes drasticallly out of nowhere, that's because I spent yesterday testing this on a private repo so I wouldn't clutter `xaynet`'s Actions history.
> DEVOPS-22 Auto cleanup stale/inactive Docker Hub tags

- .github/workflows/rust.yml
- bindings/python/Cargo.lock
- rust/Cargo.lock
- rust/Cargo.toml
- rust/xaynet-analytics/src/lib.rs
- rust/xaynet-core/src/crypto/sign.rs
- rust/xaynet-core/src/lib.rs
- rust/xaynet-core/src/message/message.rs
- rust/xaynet-mobile/src/lib.rs
- rust/xaynet-sdk/src/lib.rs
- rust/xaynet-server/src/lib.rs
- rust/xaynet-server/src/services/messages/decryptor.rs
- rust/xaynet-server/src/state_machine/initializer.rs
- rust/xaynet-server/src/state_machine/tests/initializer.rs
- rust/xaynet-server/src/storage/coordinator_storage/redis/mod.rs
- rust/xaynet-server/src/storage/model_storage/s3.rs
- rust/xaynet-server/src/storage/store.rs
- rust/xaynet-server/src/storage/tests/utils.rs
- rust/xaynet/src/lib.rs
**Summary**
- remove `xaynet-analytics` from the workspace for now
- issues between `isar` and `rustc > 1.52` need to be fixed before this can be enabled again
- tarpaulin needs to be excluded explicitely otherwise the crate still shows up with zero percent coverage
- update ci to `rustc 1.55.0`
- fix new clippy and doc lints
> Bump rustc and fix compilation

- rust/Cargo.lock
- rust/examples/Cargo.toml
- rust/xaynet-mobile/Cargo.toml
- rust/xaynet-sdk/Cargo.toml
- rust/xaynet-server/Cargo.toml
fix the following issues as far as possible:
```
Crate:         chrono
Version:       0.4.19
Title:         Potential segfault in `localtime_r` invocations
Date:          2020-11-10
ID:            RUSTSEC-2020-0159
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0159
Solution:      No safe upgrade is available!
Dependency tree: 
chrono 0.4.19
├── xaynet-server 0.2.0
│   └── xaynet 0.11.0
├── rusoto_credential 0.46.0
│   ├── rusoto_signature 0.46.0
│   │   └── rusoto_core 0.46.0
│   │       ├── xaynet-server 0.2.0
│   │       └── rusoto_s3 0.46.0
│   │           └── xaynet-server 0.2.0
│   └── rusoto_core 0.46.0
└── influxdb 0.5.2
└── xaynet-server 0.2.0
Crate:         crossbeam-deque
Version:       0.8.0
Title:         Data race in crossbeam-deque
Date:          2021-07-30
ID: …
```
> Fix security vulnerabilities
